/**
 * Typed registry of pending main-process MCP auth prompts awaiting a
 * renderer response. Replaces the previous `(global as any).__pending…`
 * pattern so the IPC handler in `ipc/mcp.ts` and the dispatcher in
 * `McpAuthService` share the same statically-typed handle map.
 *
 * Two independent maps because the response shapes are disjoint:
 *
 *   - **Consent** (`mcpAuth:showConsent` ↔ `mcpAuth:respondConsent`):
 *     yes/no decision.
 *   - **Client-id** (`mcpAuth:requestClientId` ↔ `mcpAuth:respondClientId`):
 *     either `{ cancelled: true }` or `{ clientId, clientSecret? }`.
 *
 * Keys are ephemeral request ids generated by `McpAuthService`. Handlers
 * are one-shot — they `delete` themselves after firing or being timed
 * out / aborted (handled inside `McpAuthService`).
 */

import type { McpAuthClientIdResponse } from '../../../../shared/types/mcpAuth';

export type McpAuthConsentDecision = 'cancel' | 'allow-this-time';
export type ConsentHandler = (decision: McpAuthConsentDecision) => void;
export type ClientIdHandler = (response: McpAuthClientIdResponse) => void;

class McpAuthPromptRegistry {
  private consentHandlers = new Map<string, ConsentHandler>();
  private clientIdHandlers = new Map<string, ClientIdHandler>();

  registerConsent(requestId: string, handler: ConsentHandler): void {
    this.consentHandlers.set(requestId, handler);
  }

  takeConsent(requestId: string): ConsentHandler | undefined {
    const h = this.consentHandlers.get(requestId);
    this.consentHandlers.delete(requestId);
    return h;
  }

  cancelConsent(requestId: string): void {
    this.consentHandlers.delete(requestId);
  }

  registerClientId(requestId: string, handler: ClientIdHandler): void {
    this.clientIdHandlers.set(requestId, handler);
  }

  takeClientId(requestId: string): ClientIdHandler | undefined {
    const h = this.clientIdHandlers.get(requestId);
    this.clientIdHandlers.delete(requestId);
    return h;
  }

  cancelClientId(requestId: string): void {
    this.clientIdHandlers.delete(requestId);
  }

  // ────────────────── Test-only helpers ──────────────────

  /** Test-only: list pending consent request ids (enumeration order). */
  __listConsentIdsForTests(): string[] {
    return Array.from(this.consentHandlers.keys());
  }

  /** Test-only: list pending client-id request ids. */
  __listClientIdIdsForTests(): string[] {
    return Array.from(this.clientIdHandlers.keys());
  }

  /** Test-only: drop all pending handlers. */
  __resetForTests(): void {
    this.consentHandlers.clear();
    this.clientIdHandlers.clear();
  }
}

export const mcpAuthPromptRegistry = new McpAuthPromptRegistry();
