/**
 * Tests for config/parser.ts
 */

import { describe, it, expect } from 'vitest';
import {
  parseMcpConfig,
  parseVSCodeConfigToInternal,
  formatToStandardJson,
  formatToMcpServersWrapper,
  formatToVSCodeSettings,
  formatToVSCodeMcpJson,
  isExampleConfiguration
} from '../config/parser';

// ---------------------------------------------------------------------------
// parseMcpConfig
// ---------------------------------------------------------------------------

describe('parseMcpConfig', () => {
  it('returns error on empty input', () => {
    const result = parseMcpConfig('');
    expect(result.success).toBe(false);
    expect(result.error).toContain('empty');
  });

  it('returns error on whitespace-only input', () => {
    const result = parseMcpConfig('   ');
    expect(result.success).toBe(false);
  });

  it('returns error on invalid JSON', () => {
    const result = parseMcpConfig('{ bad json }');
    expect(result.success).toBe(false);
    expect(result.error).toContain('Invalid JSON');
  });

  it('parses Format 1 – stdio basic format', () => {
    const input = JSON.stringify({ command: 'python', args: ['-m', 'server'] });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.transportType).toBe('stdio');
    expect(result.data!.config.command).toBe('python');
    expect(result.data!.config.args).toEqual(['-m', 'server']);
  });

  it('parses Format 2 – SSE/HTTP basic format', () => {
    const input = JSON.stringify({ url: 'http://localhost:8000/sse' });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.transportType).toBe('sse');
    expect(result.data!.config.url).toBe('http://localhost:8000/sse');
  });

  it('parses HTTP URL without sse as StreamableHttp', () => {
    const input = JSON.stringify({ url: 'http://localhost:8000/mcp' });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.transportType).toBe('StreamableHttp');
  });

  it('parses Format 3 – mcpServers wrapper with type=http', () => {
    const input = JSON.stringify({
      mcpServers: {
        myServer: { url: 'http://localhost:3000', type: 'http' }
      }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.serverName).toBe('myServer');
    expect(result.data!.transportType).toBe('StreamableHttp');
  });

  it('parses Format 4 – mcpServers wrapper with type=stdio', () => {
    const input = JSON.stringify({
      mcpServers: {
        myServer: { command: 'node', args: ['server.js'], type: 'stdio' }
      }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.serverName).toBe('myServer');
    expect(result.data!.transportType).toBe('stdio');
  });

  it('parses Format 5 – server fragment with type=http', () => {
    const input = JSON.stringify({
      myServer: { url: 'http://localhost:3000', type: 'http' }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.serverName).toBe('myServer');
    expect(result.data!.transportType).toBe('StreamableHttp');
  });

  it('parses Format 6 – server fragment with type=stdio', () => {
    const input = JSON.stringify({
      myServer: { command: 'npx', args: ['server'], type: 'stdio' }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.serverName).toBe('myServer');
    expect(result.data!.transportType).toBe('stdio');
  });

  it('respects currentTransportType hint when no type field', () => {
    const input = JSON.stringify({ url: 'http://localhost:3000' });
    const result = parseMcpConfig(input, 'sse');
    expect(result.success).toBe(true);
    expect(result.data!.transportType).toBe('sse');
  });

  it('includes env when present', () => {
    const input = JSON.stringify({
      command: 'node',
      args: ['srv.js'],
      env: { API_KEY: 'secret' }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.config.env).toEqual({ API_KEY: 'secret' });
  });

  it('auto-generates server name when not provided', () => {
    const input = JSON.stringify({ command: 'python', args: [] });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data!.isAutoGenerated).toBe(true);
    expect(result.data!.serverName).toMatch(/^mcp-server-/);
  });

  it('strips invisible Unicode characters before parsing', () => {
    // Wrap valid JSON with BOM and NBSP
    const input = '﻿{"command":"node","args":[]} ';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
  });

  it('handles type=sse field correctly', () => {
    const input = JSON.stringify({
      mcpServers: { s: { url: 'http://host/sse', type: 'sse' } }
    });
    const result = parseMcpConfig(input);
    expect(result.data!.transportType).toBe('sse');
  });

  it('handles type=streamable-http field correctly', () => {
    const input = JSON.stringify({
      mcpServers: { s: { url: 'http://host/mcp', type: 'streamable-http' } }
    });
    const result = parseMcpConfig(input);
    expect(result.data!.transportType).toBe('StreamableHttp');
  });
});

// ---------------------------------------------------------------------------
// parseVSCodeConfigToInternal
// ---------------------------------------------------------------------------

describe('parseVSCodeConfigToInternal', () => {
  it('returns error on empty input', () => {
    const result = parseVSCodeConfigToInternal('', 'mcp.json');
    expect(result.success).toBe(false);
  });

  it('parses mcp.json format with stdio server', () => {
    const input = JSON.stringify({
      servers: {
        myServer: { type: 'stdio', command: 'node', args: ['s.js'] }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data!.serverName).toBe('myServer');
    expect(result.data!.transportType).toBe('stdio');
    expect(result.data!.config.command).toBe('node');
  });

  it('parses settings.json format with http server', () => {
    const input = JSON.stringify({
      mcp: {
        servers: {
          remote: { type: 'http', url: 'http://localhost:3000' }
        }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'settings.json');
    expect(result.success).toBe(true);
    expect(result.data!.serverName).toBe('remote');
    expect(result.data!.transportType).toBe('StreamableHttp');
  });

  it('returns error when mcp.json has no servers section', () => {
    const input = JSON.stringify({ foo: 'bar' });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(false);
    expect(result.error).toContain('No MCP server found');
  });

  it('returns error when settings.json has no mcp.servers section', () => {
    const input = JSON.stringify({ mcp: {} });
    const result = parseVSCodeConfigToInternal(input, 'settings.json');
    expect(result.success).toBe(false);
  });

  it('returns error when servers section is empty', () => {
    const input = JSON.stringify({ servers: {} });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(false);
  });

  it('returns error on invalid JSON', () => {
    const result = parseVSCodeConfigToInternal('{ invalid', 'mcp.json');
    expect(result.success).toBe(false);
    expect(result.error).toContain('Invalid JSON');
  });

  it('includes env when present', () => {
    const input = JSON.stringify({
      servers: {
        s: { type: 'stdio', command: 'node', env: { TOKEN: 'abc' } }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data!.config.env).toEqual({ TOKEN: 'abc' });
  });

  it('detects SSE from URL ending with /sse when type=http', () => {
    const input = JSON.stringify({
      servers: { s: { type: 'http', url: 'http://host/mcp/sse' } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data!.transportType).toBe('sse');
  });
});

// ---------------------------------------------------------------------------
// formatToStandardJson
// ---------------------------------------------------------------------------

describe('formatToStandardJson', () => {
  it('formats stdio config correctly', () => {
    const parsedConfig = {
      serverName: 'test',
      transportType: 'stdio' as const,
      config: { command: 'node', args: ['s.js'] },
      isAutoGenerated: false,
      detectedFormat: 'Format 1'
    };
    const json = formatToStandardJson(parsedConfig);
    const parsed = JSON.parse(json);
    expect(parsed.command).toBe('node');
    expect(parsed.args).toEqual(['s.js']);
  });

  it('formats http config correctly', () => {
    const parsedConfig = {
      serverName: 'test',
      transportType: 'StreamableHttp' as const,
      config: { url: 'http://host/mcp' },
      isAutoGenerated: false,
      detectedFormat: 'Format 2'
    };
    const json = formatToStandardJson(parsedConfig);
    const parsed = JSON.parse(json);
    expect(parsed.url).toBe('http://host/mcp');
    expect(parsed.env).toBeUndefined();
  });

  it('omits env when empty', () => {
    const parsedConfig = {
      serverName: 'test',
      transportType: 'stdio' as const,
      config: { command: 'node', args: [], env: {} },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const json = formatToStandardJson(parsedConfig);
    const parsed = JSON.parse(json);
    expect(parsed.env).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// formatToMcpServersWrapper
// ---------------------------------------------------------------------------

describe('formatToMcpServersWrapper', () => {
  it('wraps stdio config in mcpServers', () => {
    const parsedConfig = {
      serverName: 'myServer',
      transportType: 'stdio' as const,
      config: { command: 'python', args: ['-m', 'srv'] },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const json = formatToMcpServersWrapper(parsedConfig);
    const parsed = JSON.parse(json);
    expect(parsed.mcpServers.myServer.command).toBe('python');
    expect(parsed.mcpServers.myServer.type).toBe('stdio');
  });

  it('wraps HTTP config in mcpServers', () => {
    const parsedConfig = {
      serverName: 'httpServer',
      transportType: 'StreamableHttp' as const,
      config: { url: 'http://host/mcp' },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const json = formatToMcpServersWrapper(parsedConfig);
    const parsed = JSON.parse(json);
    expect(parsed.mcpServers.httpServer.url).toBe('http://host/mcp');
    expect(parsed.mcpServers.httpServer.type).toBe('StreamableHttp');
  });
});

// ---------------------------------------------------------------------------
// formatToVSCodeSettings / formatToVSCodeMcpJson
// ---------------------------------------------------------------------------

describe('formatToVSCodeSettings', () => {
  it('produces settings.json with mcp.servers', () => {
    const configs = [
      { name: 'srv', transport: 'stdio' as const, command: 'node', args: ['s.js'] }
    ];
    const json = formatToVSCodeSettings(configs);
    const parsed = JSON.parse(json);
    expect(parsed.mcp.servers.srv.command).toBe('node');
    expect(parsed.mcp.servers.srv.type).toBe('stdio');
  });

  it('handles SSE transport', () => {
    const configs = [
      { name: 'sse-srv', transport: 'sse' as const, url: 'http://host/sse' }
    ];
    const json = formatToVSCodeSettings(configs);
    const parsed = JSON.parse(json);
    expect(parsed.mcp.servers['sse-srv'].type).toBe('sse');
    expect(parsed.mcp.servers['sse-srv'].url).toBe('http://host/sse');
  });

  it('handles StreamableHttp transport', () => {
    const configs = [
      { name: 'http-srv', transport: 'StreamableHttp' as const, url: 'http://host/mcp' }
    ];
    const json = formatToVSCodeSettings(configs);
    const parsed = JSON.parse(json);
    expect(parsed.mcp.servers['http-srv'].type).toBe('http');
  });
});

describe('formatToVSCodeMcpJson', () => {
  it('produces mcp.json with servers and inputs', () => {
    const configs = [
      { name: 'srv', transport: 'stdio' as const, command: 'python', args: ['-m', 'srv'] }
    ];
    const json = formatToVSCodeMcpJson(configs);
    const parsed = JSON.parse(json);
    expect(parsed.servers.srv.command).toBe('python');
    expect(parsed.inputs).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// isExampleConfiguration
// ---------------------------------------------------------------------------

describe('isExampleConfiguration', () => {
  it('detects stdio example template', () => {
    const stdioExample = `{
  "command": "npx|uvx|python|...",
  "args": [
    "xxx",
    "yyy"
  ],
  "env": {
    "ENV_VAR1": "value1",
    "ENV_VAR2": "value2"
  }
}`;
    expect(isExampleConfiguration(stdioExample)).toBe(true);
  });

  it('detects SSE example template', () => {
    const sseExample = `{
  "url": "http://0.0.0.0:8000/sse"
}`;
    expect(isExampleConfiguration(sseExample)).toBe(true);
  });

  it('returns false for real configuration', () => {
    const real = JSON.stringify({ command: 'node', args: ['server.js'] });
    expect(isExampleConfiguration(real)).toBe(false);
  });
});
