/** @vitest-environment happy-dom */
import { describe, it, expect } from 'vitest';
import {
  parseMcpConfig,
  formatToStandardJson,
  formatToMcpServersWrapper,
  isExampleConfiguration,
} from '../mcpConfigParser';

describe('parseMcpConfig', () => {
  describe('error cases', () => {
    it('returns error for empty input', () => {
      const result = parseMcpConfig('');
      expect(result.success).toBe(false);
      expect(result.error).toMatch(/empty/i);
    });

    it('returns error for whitespace-only input', () => {
      const result = parseMcpConfig('   ');
      expect(result.success).toBe(false);
    });

    it('returns error for invalid JSON', () => {
      const result = parseMcpConfig('not json at all');
      expect(result.success).toBe(false);
      expect(result.error).toMatch(/invalid json/i);
    });
  });

  describe('Format 1 — stdio basic', () => {
    it('parses command + args', () => {
      const input = JSON.stringify({ command: 'npx', args: ['-y', 'my-mcp'] });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('stdio');
      expect(result.data!.config.command).toBe('npx');
      expect(result.data!.config.args).toEqual(['-y', 'my-mcp']);
      expect(result.data!.detectedFormat).toContain('Format 1');
    });

    it('auto-generates server name for bare stdio config', () => {
      const input = JSON.stringify({ command: 'uvx', args: ['tool'] });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.isAutoGenerated).toBe(true);
      expect(result.data!.serverName).toMatch(/^mcp-server-/);
    });

    it('includes env when present', () => {
      const input = JSON.stringify({ command: 'npx', args: [], env: { TOKEN: 'abc' } });
      const result = parseMcpConfig(input);
      expect(result.data!.config.env).toEqual({ TOKEN: 'abc' });
    });

    it('omits env when empty', () => {
      const input = JSON.stringify({ command: 'npx', args: [], env: {} });
      const result = parseMcpConfig(input);
      expect(result.data!.config.env).toBeUndefined();
    });
  });

  describe('Format 2 — StreamableHttp basic', () => {
    it('parses URL config', () => {
      const input = JSON.stringify({ url: 'http://localhost:8000/mcp' });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('StreamableHttp');
      expect(result.data!.config.url).toBe('http://localhost:8000/mcp');
      expect(result.data!.detectedFormat).toContain('Format 2');
    });
  });

  describe('Format 3/4 — mcpServers wrapper with type', () => {
    it('parses StreamableHttp mcpServers wrapper', () => {
      const input = JSON.stringify({
        mcpServers: {
          'my-server': { url: 'http://localhost:8000', type: 'http' }
        }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('StreamableHttp');
      expect(result.data!.serverName).toBe('my-server');
      expect(result.data!.isAutoGenerated).toBe(false);
      expect(result.data!.detectedFormat).toContain('Format 3');
    });

    it('parses stdio mcpServers wrapper with type', () => {
      const input = JSON.stringify({
        mcpServers: {
          'my-stdio': { command: 'npx', args: ['-y', 'tool'], type: 'stdio' }
        }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('stdio');
      expect(result.data!.serverName).toBe('my-stdio');
      expect(result.data!.detectedFormat).toContain('Format 4');
    });
  });

  describe('Format 7/8 — mcpServers wrapper without type', () => {
    it('auto-detects stdio when command present', () => {
      const input = JSON.stringify({
        mcpServers: {
          'calc': { command: 'python', args: ['server.py'] }
        }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('stdio');
      expect(result.data!.detectedFormat).toContain('Format 8');
    });

    it('auto-detects StreamableHttp when url present', () => {
      const input = JSON.stringify({
        mcpServers: {
          'remote': { url: 'http://example.com/mcp' }
        }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('StreamableHttp');
      expect(result.data!.detectedFormat).toContain('Format 7');
    });
  });

  describe('Format 5/6 — server fragment with type', () => {
    it('parses StreamableHttp fragment', () => {
      const input = JSON.stringify({
        'my-server': { url: 'http://localhost:8000', type: 'http' }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('StreamableHttp');
      expect(result.data!.serverName).toBe('my-server');
      expect(result.data!.detectedFormat).toContain('Format 5');
    });

    it('parses stdio fragment', () => {
      const input = JSON.stringify({
        'calc': { command: 'npx', args: ['-y', 'calc'], type: 'stdio' }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('stdio');
      expect(result.data!.serverName).toBe('calc');
      expect(result.data!.detectedFormat).toContain('Format 6');
    });
  });

  describe('Format 9/10 — minimal fragment without type', () => {
    it('auto-detects StreamableHttp from URL in fragment', () => {
      const input = JSON.stringify({
        'remote-tool': { url: 'http://remote.example.com/mcp' }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('StreamableHttp');
      expect(result.data!.detectedFormat).toContain('Format 9');
    });

    it('auto-detects stdio from command in fragment', () => {
      const input = JSON.stringify({
        'local-tool': { command: 'python', args: ['server.py'] }
      });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
      expect(result.data!.transportType).toBe('stdio');
      expect(result.data!.detectedFormat).toContain('Format 10');
    });
  });

  describe('invisible character cleaning', () => {
    it('handles NBSP in JSON', () => {
      // Replace spaces around colon with NBSP
      const dirtyJson = '{ "command": "npx", "args": []}';
      const result = parseMcpConfig(dirtyJson);
      expect(result.success).toBe(true);
    });

    it('handles BOM-prefixed JSON', () => {
      const input = '﻿' + JSON.stringify({ command: 'npx', args: [] });
      const result = parseMcpConfig(input);
      expect(result.success).toBe(true);
    });
  });

  describe('currentTransportType hint', () => {
    it('keeps sse when url present and user selected sse', () => {
      const input = JSON.stringify({ url: 'http://example.com' });
      const result = parseMcpConfig(input, 'sse');
      expect(result.data!.transportType).toBe('sse');
    });

    it('promotes to StreamableHttp when currently stdio but url present', () => {
      const input = JSON.stringify({ url: 'http://example.com' });
      const result = parseMcpConfig(input, 'stdio');
      expect(result.data!.transportType).toBe('StreamableHttp');
    });
  });
});

describe('formatToStandardJson', () => {
  it('formats stdio config correctly', () => {
    const json = formatToStandardJson({
      serverName: 'test',
      transportType: 'stdio',
      config: { command: 'npx', args: ['-y', 'tool'] },
      isAutoGenerated: false,
      detectedFormat: 'Format 1',
    });
    const parsed = JSON.parse(json);
    expect(parsed.command).toBe('npx');
    expect(parsed.args).toEqual(['-y', 'tool']);
    expect(parsed.url).toBeUndefined();
  });

  it('formats HTTP config correctly', () => {
    const json = formatToStandardJson({
      serverName: 'test',
      transportType: 'StreamableHttp',
      config: { url: 'http://example.com' },
      isAutoGenerated: false,
      detectedFormat: 'Format 2',
    });
    const parsed = JSON.parse(json);
    expect(parsed.url).toBe('http://example.com');
    expect(parsed.command).toBeUndefined();
  });

  it('includes env in stdio output when non-empty', () => {
    const json = formatToStandardJson({
      serverName: 'test',
      transportType: 'stdio',
      config: { command: 'npx', args: [], env: { TOKEN: 'abc' } },
      isAutoGenerated: false,
      detectedFormat: 'Format 1',
    });
    expect(JSON.parse(json).env).toEqual({ TOKEN: 'abc' });
  });

  it('omits env in output when empty', () => {
    const json = formatToStandardJson({
      serverName: 'test',
      transportType: 'stdio',
      config: { command: 'npx', args: [], env: {} },
      isAutoGenerated: false,
      detectedFormat: 'Format 1',
    });
    expect(JSON.parse(json).env).toBeUndefined();
  });
});

describe('formatToMcpServersWrapper', () => {
  it('wraps stdio config in mcpServers', () => {
    const json = formatToMcpServersWrapper({
      serverName: 'my-tool',
      transportType: 'stdio',
      config: { command: 'npx', args: ['-y', 'tool'] },
      isAutoGenerated: false,
      detectedFormat: 'Format 1',
    });
    const parsed = JSON.parse(json);
    expect(parsed.mcpServers['my-tool'].command).toBe('npx');
    expect(parsed.mcpServers['my-tool'].type).toBe('stdio');
  });

  it('wraps StreamableHttp config in mcpServers', () => {
    const json = formatToMcpServersWrapper({
      serverName: 'remote',
      transportType: 'StreamableHttp',
      config: { url: 'http://example.com' },
      isAutoGenerated: false,
      detectedFormat: 'Format 2',
    });
    const parsed = JSON.parse(json);
    expect(parsed.mcpServers['remote'].url).toBe('http://example.com');
    expect(parsed.mcpServers['remote'].type).toBe('StreamableHttp');
  });
});

describe('isExampleConfiguration', () => {
  it('recognizes the stdio example template', () => {
    const exampleInput = `{
  "command": "npx|uvx|python|...",
  "args": [
    "xxx",
    "yyy"
  ],
  "env": {
    "ENV_VAR1": "value1",
    "ENV_VAR2": "value2"
  }
}`;
    expect(isExampleConfiguration(exampleInput)).toBe(true);
  });

  it('recognizes the SSE example template', () => {
    const exampleInput = `{
  "url": "http://0.0.0.0:8000/sse"
}`;
    expect(isExampleConfiguration(exampleInput)).toBe(true);
  });

  it('returns false for real configuration', () => {
    const realConfig = JSON.stringify({ command: 'npx', args: ['-y', 'my-tool'] });
    expect(isExampleConfiguration(realConfig)).toBe(false);
  });
});
