/**
 * Configuration Parser
 * VSCode MCP Client configuration parsing and format conversion
 */

import { 
  ParsedMcpConfig, 
  McpConfigParseResult, 
  McpServerConfig,
  KosmosAppMCPServerConfig,
  TransportType 
} from './types';
import { 
  validateJsonFormat, 
  detectConfigFormat, 
  safeJsonParse 
} from './utils';

// ==================== Main Configuration Parsing Functions ====================

/**
 * Parse MCP configuration and detect format
 */
export function parseMcpConfig(
  input: string, 
  currentTransportType?: TransportType
): McpConfigParseResult {
  try {
    if (!input.trim()) {
      return {
        success: false,
        error: 'Configuration cannot be empty'
      };
    }

    // Clean invisible characters
    const cleanedInput = cleanInvisibleCharacters(input.trim());
    
    // Validate JSON format
    const jsonValidation = validateJsonFormat(cleanedInput);
    if (!jsonValidation.isValid) {
      return {
        success: false,
        error: `Invalid JSON format: ${jsonValidation.error}`
      };
    }

    // Parse JSON
    const parseResult = safeJsonParse(cleanedInput);
    if (!parseResult.success || !parseResult.data) {
      return {
        success: false,
        error: `JSON parse failed: ${parseResult.error}`
      };
    }

    const parsedConfig = parseResult.data;

    // Extract server name and configuration
    const extractedServerName = extractServerName(parsedConfig);
    const extractedConfig = extractConfigFromFormat(parsedConfig);
    
    let detectedFormat = '';
    let serverName = extractedServerName;
    let transportType: 'stdio' | 'sse' | 'StreamableHttp';
    let config: ParsedMcpConfig['config'] = {};
    
    // Determine format and extract data
    if (parsedConfig.mcpServers) {
      // Formats 3, 4, 7, 8 (mcpServers wrapper)
      if (extractedConfig.type) {
        transportType = getTransportTypeFromTypeField(extractedConfig.type);
        if (transportType === 'stdio') {
          detectedFormat = 'Format 4: Stdio full configuration';
        } else {
          detectedFormat = 'Format 3: StreamableHttp full configuration';
        }
      } else {
        // Formats 7, 8 (no type field)
        transportType = autoDetectTransportType(extractedConfig, currentTransportType);
        if (transportType === 'stdio') {
          detectedFormat = 'Format 8: Stdio simplified format';
        } else {
          detectedFormat = 'Format 7: StreamableHttp simplified format';
        }
      }
    } else if (extractedConfig.serverName || (Object.keys(parsedConfig).length === 1 && typeof parsedConfig[Object.keys(parsedConfig)[0]] === 'object')) {
      // Formats 5, 6, 9, 10 (server fragments)
      if (extractedConfig.type) {
        transportType = getTransportTypeFromTypeField(extractedConfig.type);
        if (transportType === 'stdio') {
          detectedFormat = 'Format 6: Stdio server fragment';
        } else {
          detectedFormat = 'Format 5: StreamableHttp server fragment';
        }
      } else {
        // Formats 9, 10 (no type field)
        transportType = autoDetectTransportType(extractedConfig, currentTransportType);
        if (transportType === 'stdio') {
          detectedFormat = 'Format 10: Stdio minimal fragment';
        } else {
          detectedFormat = 'Format 9: StreamableHttp minimal fragment';
        }
      }
      
      // Extract server name from fragment format
      if (!serverName && !extractedConfig.serverName) {
        const keys = Object.keys(parsedConfig);
        if (keys.length === 1) {
          serverName = keys[0];
        }
      } else if (extractedConfig.serverName) {
        serverName = extractedConfig.serverName;
      }
    } else {
      // Formats 1, 2 (basic format)
      transportType = autoDetectTransportType(extractedConfig, currentTransportType);
      if (transportType === 'stdio') {
        detectedFormat = 'Format 1: Stdio basic format';
      } else {
        detectedFormat = 'Format 2: SSE/StreamableHttp basic format';
      }
    }

    // Extract configuration fields
    if (transportType === 'stdio') {
      config.command = extractedConfig.command;
      config.args = extractedConfig.args;
      if (extractedConfig.env && Object.keys(extractedConfig.env).length > 0) {
        config.env = extractedConfig.env;
      }
    } else {
      config.url = extractedConfig.url;
      if (extractedConfig.env && Object.keys(extractedConfig.env).length > 0) {
        config.env = extractedConfig.env;
      }
    }

    // Generate server name (if not provided)
    const isAutoGenerated = !serverName;
    if (!serverName) {
      serverName = generateServerName();
    }

    return {
      success: true,
      data: {
        serverName,
        transportType,
        config,
        isAutoGenerated,
        detectedFormat
      }
    };

  } catch (error) {
    return {
      success: false,
      error: `Parse error: ${error instanceof Error ? error.message : 'unknown error'}`
    };
  }
}

/**
 * Parse VSCode format and convert to internal format
 */
export function parseVSCodeConfigToInternal(
  input: string,
  format: 'settings.json' | 'mcp.json'
): McpConfigParseResult {
  try {
    if (!input.trim()) {
      return {
        success: false,
        error: 'Configuration cannot be empty'
      };
    }

    // Clean invisible characters
    const cleanedInput = cleanInvisibleCharacters(input.trim());
    
    // Validate JSON format
    const jsonValidation = validateJsonFormat(cleanedInput);
    if (!jsonValidation.isValid) {
      return {
        success: false,
        error: `Invalid JSON format: ${jsonValidation.error}`
      };
    }

    // Parse JSON
    const parseResult = safeJsonParse(cleanedInput);
    if (!parseResult.success || !parseResult.data) {
      return {
        success: false,
        error: `JSON parse failed: ${parseResult.error}`
      };
    }

    const parsedConfig = parseResult.data;

    // Extract servers based on format
    let servers: Record<string, any> = {};
    
    if (format === 'settings.json' && parsedConfig.mcp?.servers) {
      servers = parsedConfig.mcp.servers;
    } else if (format === 'mcp.json' && parsedConfig.servers) {
      servers = parsedConfig.servers;
    } else {
      return {
        success: false,
        error: 'No MCP servers found in configuration'
      };
    }

    // If there are multiple servers, return the first one (compatible with existing parser)
    const serverNames = Object.keys(servers);
    if (serverNames.length === 0) {
      return {
        success: false,
        error: 'No MCP servers found in configuration'
      };
    }

    const firstServerName = serverNames[0];
    const firstServerConfig = servers[firstServerName];

    // Convert to internal format
    const transportType = convertVSCodeTransportType(firstServerConfig);
    
    const config: ParsedMcpConfig['config'] = {};
    
    if (transportType === 'stdio') {
      config.command = firstServerConfig.command;
      config.args = firstServerConfig.args;
      if (firstServerConfig.env && Object.keys(firstServerConfig.env).length > 0) {
        config.env = firstServerConfig.env;
      }
    } else {
      config.url = firstServerConfig.url;
      if (firstServerConfig.env && Object.keys(firstServerConfig.env).length > 0) {
        config.env = firstServerConfig.env;
      }
    }

    return {
      success: true,
      data: {
        serverName: firstServerName,
        transportType,
        config,
        isAutoGenerated: false,
        detectedFormat: `VSCode ${format} format`
      }
    };

  } catch (error) {
    return {
      success: false,
      error: `Parse error: ${error instanceof Error ? error.message : 'unknown error'}`
    };
  }
}

// ==================== Format Conversion Functions ====================

/**
 * Format parsed configuration to standard JSON format
 */
export function formatToStandardJson(parsedConfig: ParsedMcpConfig): string {
  const { transportType, config } = parsedConfig;
  
  if (transportType === 'stdio') {
    const stdioConfig: any = {
      command: config.command,
      args: config.args
    };
    
    if (config.env && Object.keys(config.env).length > 0) {
      stdioConfig.env = config.env;
    }
    
    return JSON.stringify(stdioConfig, null, 2);
  } else {
    const httpConfig: any = {
      url: config.url
    };
    
    if (config.env && Object.keys(config.env).length > 0) {
      httpConfig.env = config.env;
    }
    
    return JSON.stringify(httpConfig, null, 2);
  }
}

/**
 * Format to complete mcpServers wrapper format
 */
export function formatToMcpServersWrapper(parsedConfig: ParsedMcpConfig): string {
  const { serverName, transportType, config } = parsedConfig;
  
  const serverConfig: any = {};
  
  if (transportType === 'stdio') {
    serverConfig.command = config.command;
    serverConfig.args = config.args;
    serverConfig.type = 'stdio';
  } else {
    serverConfig.url = config.url;
    serverConfig.type = transportType;
  }
  
  if (config.env && Object.keys(config.env).length > 0) {
    serverConfig.env = config.env;
  }
  
  const wrapper = {
    mcpServers: {
      [serverName!]: serverConfig
    }
  };
  
  return JSON.stringify(wrapper, null, 2);
}

/**
 * Convert Kosmos server configuration to VSCode format (settings.json style)
 */
export function formatToVSCodeSettings(serverConfigs: KosmosAppMCPServerConfig[]): string {
  const servers: Record<string, any> = {};
  
  for (const config of serverConfigs) {
    const vscodeConfig: any = {};
    
    if (config.transport === 'stdio') {
      vscodeConfig.type = 'stdio';
      vscodeConfig.command = config.command;
      if (config.args && config.args.length > 0) {
        vscodeConfig.args = config.args;
      }
    } else {
      // For sse and StreamableHttp, use url
      vscodeConfig.url = config.url;
      
      // Set appropriate type
      if (config.transport === 'sse') {
        vscodeConfig.type = 'sse';
      } else if (config.transport === 'StreamableHttp') {
        vscodeConfig.type = 'http';
      }
    }
    
    // Add environment variables (if present)
    if (config.env && Object.keys(config.env).length > 0) {
      vscodeConfig.env = config.env;
    }
    
    servers[config.name] = vscodeConfig;
  }
  
  const settingsFormat = {
    mcp: {
      servers: servers
    }
  };
  
  return JSON.stringify(settingsFormat, null, 2);
}

/**
 * Convert Kosmos server configuration to VSCode mcp.json format (Windows style)
 */
export function formatToVSCodeMcpJson(serverConfigs: KosmosAppMCPServerConfig[]): string {
  const servers: Record<string, any> = {};
  
  for (const config of serverConfigs) {
    const vscodeConfig: any = {};
    
    if (config.transport === 'stdio') {
      vscodeConfig.type = 'stdio';
      vscodeConfig.command = config.command;
      if (config.args && config.args.length > 0) {
        vscodeConfig.args = config.args;
      }
    } else {
      // For sse and StreamableHttp, use url
      vscodeConfig.url = config.url;
      
      // Set appropriate type
      if (config.transport === 'sse') {
        vscodeConfig.type = 'sse';
      } else if (config.transport === 'StreamableHttp') {
        vscodeConfig.type = 'http';
      }
    }
    
    // Add environment variables (if present)
    if (config.env && Object.keys(config.env).length > 0) {
      vscodeConfig.env = config.env;
    }
    
    servers[config.name] = vscodeConfig;
  }
  
  const mcpJsonFormat = {
    servers: servers,
    inputs: []
  };
  
  return JSON.stringify(mcpJsonFormat, null, 2);
}

// ==================== Utility Functions ====================

/**
 * Generate a timestamp-based server name
 */
function generateServerName(): string {
  const now = new Date();
  const timestamp = now.toISOString()
    .replace(/[-:T]/g, '')
    .replace(/\.\d{3}Z$/, '')
    .slice(0, 14); // YYYYMMDDHHMMSS
  return `mcp-server-${timestamp}`;
}

/**
 * Clean invisible characters that may cause JSON parsing issues
 */
function cleanInvisibleCharacters(text: string): string {
  return text
    .replace(/\u00A0/g, ' ')  // Replace NBSP (non-breaking space) with regular space
    .replace(/\u202F/g, ' ')  // Replace narrow non-breaking space
    .replace(/\u2060/g, '')   // Remove word joiner
    .replace(/\uFEFF/g, '')   // Remove byte order mark (BOM)
    .replace(/\u180E/g, ' ')  // Replace Mongolian vowel separator
    .replace(/\u200B/g, '')   // Remove zero-width space
    .replace(/\u200C/g, '')   // Remove zero-width non-joiner
    .replace(/\u200D/g, '');  // Remove zero-width joiner
}

/**
 * Determine transport type based on the type field value
 */
function getTransportTypeFromTypeField(type: string): 'stdio' | 'sse' | 'StreamableHttp' {
  const lowerType = type.toLowerCase();
  if (lowerType === 'stdio') {
    return 'stdio';
  }
  if (lowerType === 'sse') {
    return 'sse';
  }
  if (['streamable-http', 'http', 'streamablehttp'].includes(lowerType)) {
    return 'StreamableHttp';
  }
  return 'StreamableHttp'; // Default
}

/**
 * Auto-detect transport type based on configuration content
 */
function autoDetectTransportType(config: any, currentType?: TransportType): 'stdio' | 'sse' | 'StreamableHttp' {
  if (config.command || config.args) {
    return 'stdio';
  }
  if (config.url) {
    const url = config.url.toLowerCase();
    
    // Enhanced SSE endpoint detection
    if (url.includes('/sse') ||
        url.includes('/mcp/sse') ||
        url.includes('text/event-stream') ||
        url.endsWith('/sse')) {
      return 'sse';
    }
    
    // Apply format 2 rule: if current is stdio, auto-select StreamableHttp
    if (currentType === 'stdio') {
      return 'StreamableHttp';
    }
    // If user selected sse, keep it unchanged
    if (currentType === 'sse') {
      return 'sse';
    }
    return 'StreamableHttp';
  }
  return (currentType as any) || 'stdio';
}

/**
 * Extract server name from mcpServers wrapper or generate one
 */
function extractServerName(parsedConfig: any): string | undefined {
  if (parsedConfig.mcpServers && typeof parsedConfig.mcpServers === 'object') {
    const serverNames = Object.keys(parsedConfig.mcpServers);
    if (serverNames.length > 0) {
      return serverNames[0]; // Take the first server name
    }
  }
  return undefined;
}

/**
 * Extract configuration from various format structures
 */
function extractConfigFromFormat(parsedConfig: any): any {
  // Formats 3-6: mcpServers wrapper
  if (parsedConfig.mcpServers && typeof parsedConfig.mcpServers === 'object') {
    const serverNames = Object.keys(parsedConfig.mcpServers);
    if (serverNames.length > 0) {
      return parsedConfig.mcpServers[serverNames[0]];
    }
  }
  
  // Formats 5-6, 9-10: Server fragment (direct object with server name as key)
  const keys = Object.keys(parsedConfig);
  if (keys.length === 1 && typeof parsedConfig[keys[0]] === 'object' && parsedConfig[keys[0]] !== null) {
    const serverConfig = parsedConfig[keys[0]];
    // Check if this looks like a server config (has command/args or url)
    if (serverConfig.command || serverConfig.args || serverConfig.url || serverConfig.type) {
      return { serverName: keys[0], ...serverConfig };
    }
  }
  
  // Formats 1-2: Direct configuration
  return parsedConfig;
}

/**
 * Convert VSCode transport type to internal transport type
 */
function convertVSCodeTransportType(vscodeConfig: any): 'stdio' | 'sse' | 'StreamableHttp' {
  if (vscodeConfig.type) {
    const lowerType = vscodeConfig.type.toLowerCase();
    switch (lowerType) {
      case 'stdio':
        return 'stdio';
      case 'sse':
        return 'sse';
      case 'http':
      case 'streamablehttp':
        // Enhanced URL analysis for HTTP type
        if (vscodeConfig.url) {
          const url = vscodeConfig.url.toLowerCase();
          if (url.includes('/sse') ||
              url.includes('/mcp/sse') ||
              url.includes('text/event-stream') ||
              url.endsWith('/sse')) {
            return 'sse';
          }
        }
        return 'StreamableHttp';
      default:
        // Continue auto-detection
        break;
    }
  }

  // Auto-detect based on available fields
  if (vscodeConfig.command || vscodeConfig.args) {
    return 'stdio';
  }

  if (vscodeConfig.url) {
    const url = vscodeConfig.url.toLowerCase();
    // Enhanced URL pattern detection for specific cases
    if (url.includes('/sse') ||
        url.includes('/mcp/sse') ||
        url.includes('text/event-stream') ||
        url.endsWith('/sse')) {
      return 'sse';
    }
    
    // Special handling for chrome-mcp and similar HTTP endpoints
    if (url.includes('/mcp') && !url.includes('/sse')) {
      return 'StreamableHttp';
    }
    
    return 'StreamableHttp';
  }

  // Default fallback
  return 'stdio';
}

/**
 * Validate if a configuration is an example template (should be rejected)
 */
export function isExampleConfiguration(input: string): boolean {
  const stdioExample = `{
  "command": "npx|uvx|python|...",
  "args": [
    "xxx",
    "yyy"
  ],
  "env": {
    "ENV_VAR1": "value1",
    "ENV_VAR2": "value2"
  }
}`;

  const sseExample = `{
  "url": "http://0.0.0.0:8000/sse"
}`;

  const normalizedInput = input.replace(/\s+/g, ' ').trim();
  const normalizedStdioExample = stdioExample.replace(/\s+/g, ' ').trim();
  const normalizedSseExample = sseExample.replace(/\s+/g, ' ').trim();

  return normalizedInput === normalizedStdioExample || normalizedInput === normalizedSseExample;
}