/**
 * Configuration Adapter Type Definitions
 * VSCode MCP Client configuration compatibility integration
 */

// ==================== Configuration Type Definitions ====================

export interface McpServerConfig {
  name: string;
  transport: 'stdio' | 'http' | 'sse';
  command?: string;
  args?: string[];
  url?: string;
  env?: Record<string, string>;
  workingDirectory?: string;
  disabled?: boolean;
  trusted?: boolean;
}

export type TransportType = 'stdio' | 'http' | 'sse';

// ==================== VSCode Configuration Compatibility Types ====================

export interface VscodeConfigFile {
  path: string;
  expandedPath: string;
  exists: boolean;
  isValid: boolean;
  isReadable: boolean;
  serverCount: number;
  fileSize?: number;
  lastModified?: number;
  error?: string;
  detectedFormat: 'settings.json' | 'mcp.json' | 'unknown';
}

export interface VscodeConfigDetectionResult {
  success: boolean;
  platform: string;
  isSupported: boolean;
  configFiles: VscodeConfigFile[];
  totalServersFound: number;
  error?: string;
}

export interface ParsedMcpConfig {
  serverName?: string;
  transportType: 'stdio' | 'sse' | 'StreamableHttp';
  config: {
    command?: string;
    args?: string[];
    url?: string;
    env?: Record<string, string>;
  };
  isAutoGenerated: boolean;
  detectedFormat: string;
}

export interface McpConfigParseResult {
  success: boolean;
  data?: ParsedMcpConfig;
  error?: string;
}

export interface ConfigValidationReport {
  serverName: string;
  isValid: boolean;
  errors: string[];
  warnings: string[];
  info: string[];
  score: number; // 0-100, quality score
}

export interface ValidationRuleResult {
  passed: boolean;
  message?: string;
}

export interface PlatformInfo {
  platform: string;
  isSupported: boolean;
  vscodeConfigPath: string;
  vscodeConfigPaths: string[];
  displayName: string;
}

// ==================== Kosmos Compatibility Types ====================

export interface KosmosAppMCPServerConfig {
  name: string;
  transport: 'stdio' | 'sse' | 'StreamableHttp';
  command?: string;
  args?: string[];
  url?: string;
  env?: Record<string, string>;
  version?: string;
  source?: 'ON-DEVICE';
}

export interface ImportValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  serverCount: number;
}

export interface VSCodeMCPServerConfig {
  type?: string;
  command?: string;
  args?: string[];
  url?: string;
  env?: Record<string, string>;
  disabled?: boolean;
}

// ==================== Configuration Adapter Interface ====================

export interface ConfigAdapterOptions {
  /** Enable automatic configuration detection */
  autoDetection?: boolean;
  /** Configuration validation strict mode */
  strictValidation?: boolean;
  /** Supported platforms */
  supportedPlatforms?: string[];
  /** Custom configuration paths */
  customConfigPaths?: string[];
  /** Cache configuration time (milliseconds) */
  cacheTtl?: number;
}

export interface ConfigMigrationResult {
  success: boolean;
  migratedConfigs: McpServerConfig[];
  errors: string[];
  warnings: string[];
  skippedConfigs: number;
  originalFormat: string;
  targetFormat: string;
}

export interface ConfigDetectionState {
  isDetecting: boolean;
  lastDetection?: Date;
  detectedConfigs: VscodeConfigFile[];
  platformInfo: PlatformInfo;
  supportedFormats: string[];
}

export interface ConfigAdapterEvents {
  'detection-started': () => void;
  'detection-completed': (result: VscodeConfigDetectionResult) => void;
  'detection-failed': (error: Error) => void;
  'config-validated': (report: ConfigValidationReport) => void;
  'config-migrated': (result: ConfigMigrationResult) => void;
  'platform-changed': (platformInfo: PlatformInfo) => void;
}

// ==================== Utility Function Types ====================

export interface FileSystemResult<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

export interface FileExistsResult {
  exists: boolean;
  error?: string;
}

export interface FileReadableResult {
  readable: boolean;
  error?: string;
}

export interface FileStatsResult {
  success: boolean;
  stats?: {
    size: number;
    lastModified: number;
  };
  error?: string;
}

export interface FileContentResult {
  success: boolean;
  content?: string;
  error?: string;
}

// ==================== Type Guard Functions ====================

export function isTransportType(type: string): type is TransportType {
  return ['stdio', 'http', 'sse'].includes(type);
}

export function isMcpServerConfig(obj: any): obj is McpServerConfig {
  return obj && 
    typeof obj.name === 'string' && 
    isTransportType(obj.transport);
}

export function isParsedMcpConfig(obj: any): obj is ParsedMcpConfig {
  return obj && 
    typeof obj.transportType === 'string' && 
    obj.config !== undefined;
}

// ==================== Default Configuration ====================

export const DEFAULT_CONFIG_ADAPTER_OPTIONS: Required<ConfigAdapterOptions> = {
  autoDetection: true,
  strictValidation: false,
  supportedPlatforms: ['macOS', 'Windows', 'Linux'],
  customConfigPaths: [],
  cacheTtl: 5 * 60 * 1000, // 5 minutes
};

// ==================== Constant Definitions ====================

export const SUPPORTED_CONFIG_FORMATS = [
  'settings.json',
  'mcp.json',
  'kosmos.json'
] as const;

export const SUPPORTED_TRANSPORT_TYPES = [
  'stdio',
  'http',
  'sse'
] as const;

export const PLATFORM_NAMES = {
  macOS: 'macOS',
  Windows: 'Windows',
  Linux: 'Linux'
} as const;

export type SupportedConfigFormat = typeof SUPPORTED_CONFIG_FORMATS[number];
export type SupportedTransportType = typeof SUPPORTED_TRANSPORT_TYPES[number];
export type SupportedPlatform = keyof typeof PLATFORM_NAMES;