// src/main/lib/evalHarness/evalHttpServer.ts
import * as http from 'http';
import { randomUUID } from 'crypto';
import {
  RunTestBodySchema,
  JudgeBodySchema,
  type RunTestRequest,
  type RunTestResponse,
  type JudgeRequest,
} from './evalProtocol';
import { EvalAgentRunner } from './evalAgentRunner';
import { EvalJudgeRunner } from './evalJudgeRunner';

const DEFAULT_PORT = 8100;
const HOST = '127.0.0.1';
const MAX_BODY_SIZE = 1024 * 1024; // 1MB — agent prompts can be large
const MAX_CONCURRENT_RUNS = 2;
const RUN_TIMEOUT_MS = 10 * 60 * 1000; // 10 minutes

/**
 * HTTP server for AgenticEval integration.
 * Exposes /eval/health, /eval/run, /eval/judge endpoints.
 *
 * Security:
 * - All endpoints (except health) require Bearer token authentication.
 *   The token is read from the EVAL_AUTH_TOKEN environment variable,
 *   which is set by the AgenticEval orchestrator before launching OpenKosmos.
 *   If the env var is missing, the server refuses to start.
 * - No CORS headers — localhost-to-localhost doesn't need them and
 *   omitting them blocks browser-originated cross-origin requests.
 */
export class EvalHttpServer {
  private server: http.Server | null = null;
  private agentRunner: EvalAgentRunner;
  private judgeRunner: EvalJudgeRunner;
  private port: number;
  private readonly authToken: string;
  private activeRuns: number = 0;

  constructor(userAlias: string, port?: number) {
    const token = process.env.EVAL_AUTH_TOKEN;
    if (!token) {
      throw new Error(
        'EVAL_AUTH_TOKEN environment variable is required. ' +
        'Set it to the token generated by AgenticEval before launching eval mode.'
      );
    }
    this.authToken = token;
    this.agentRunner = new EvalAgentRunner(userAlias);
    this.judgeRunner = new EvalJudgeRunner(userAlias);
    this.port = port ?? this.getPortFromArgs() ?? DEFAULT_PORT;
  }

  /**
   * Start the HTTP server. Resolves when listening.
   */
  async start(): Promise<void> {
    return new Promise((resolve, reject) => {
      this.server = http.createServer((req, res) => {
        this.handleRequest(req, res);
      });

      this.server.on('error', (err: NodeJS.ErrnoException) => {
        if (err.code === 'EADDRINUSE') {
          console.error(`[EvalHttpServer] Port ${this.port} is already in use`);
        }
        reject(err);
      });

      this.server.listen(this.port, HOST, () => {
        // Update port to the actual assigned port (important when port=0)
        const addr = this.server!.address();
        if (addr && typeof addr === 'object') {
          this.port = addr.port;
        }
        console.error(`[EvalHttpServer] Listening on http://${HOST}:${this.port}/eval/`);
        resolve();
      });
    });
  }

  /**
   * Stop the HTTP server.
   */
  stop(): Promise<void> {
    return new Promise((resolve) => {
      this.agentRunner.destroyAllSessions();
      if (this.server) {
        this.server.close(() => {
          this.server = null;
          resolve();
        });
      } else {
        resolve();
      }
    });
  }

  getPort(): number {
    return this.port;
  }

  /**
   * Route incoming HTTP requests.
   */
  private handleRequest(req: http.IncomingMessage, res: http.ServerResponse): void {
    const url = new URL(req.url || '/', `http://${HOST}`);
    const pathname = url.pathname;
    const method = req.method?.toUpperCase();

    // Block CORS preflight — no cross-origin access allowed
    if (method === 'OPTIONS') {
      res.writeHead(403);
      res.end();
      return;
    }

    // Health check is unauthenticated (needed for readiness probes)
    if (pathname === '/eval/health' && method === 'GET') {
      this.sendJson(res, 200, { status: 'ok' });
      return;
    }

    // All other endpoints require Bearer token authentication
    if (!this.checkAuth(req, res)) return;

    if (pathname === '/eval/run' && method === 'POST') {
      this.readJsonBody(req, res, (body) => {
        void this.handleRun(body, res);
      });
    } else if (pathname === '/eval/judge' && method === 'POST') {
      this.readJsonBody(req, res, (body) => {
        void this.handleJudge(body, res);
      });
    } else {
      this.sendJson(res, 404, { error: `Not found: ${method} ${pathname}` });
    }
  }

  /**
   * Handle POST /eval/run — full agent e2e loop.
   * Enforces concurrency limit and per-request timeout.
   */
  private async handleRun(body: unknown, res: http.ServerResponse): Promise<void> {
    const parseResult = RunTestBodySchema.safeParse(body);
    if (!parseResult.success) {
      const detail = parseResult.error.issues
        .map((i) => `${i.path.join('.')}: ${i.message}`)
        .join('; ');
      this.sendJson(res, 400, { error: `Invalid request body: ${detail}` });
      return;
    }

    if (this.activeRuns >= MAX_CONCURRENT_RUNS) {
      this.sendJson(res, 429, {
        error: `Too many concurrent requests (limit: ${MAX_CONCURRENT_RUNS}). Try again later.`,
      });
      return;
    }

    const { prompt, metadata, session_id } = parseResult.data;
    const requestId = randomUUID();

    const runTestRequest: RunTestRequest = {
      type: 'run_test',
      id: requestId,
      data: { prompt, metadata },
      session_id,
    };

    this.activeRuns++;
    try {
      console.error(`[EvalHttpServer] /eval/run started (id=${requestId}, active=${this.activeRuns})`);

      const abortController = new AbortController();
      const timeoutId = setTimeout(() => abortController.abort(), RUN_TIMEOUT_MS);
      const timeoutPromise = new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error(`Request timed out after ${RUN_TIMEOUT_MS / 1000}s`)), RUN_TIMEOUT_MS)
      );

      let result: RunTestResponse;
      try {
        result = await Promise.race([
          session_id
            ? this.agentRunner.run(runTestRequest)
            : this.agentRunner.runOneShot(runTestRequest, abortController.signal),
          timeoutPromise,
        ]);
      } finally {
        clearTimeout(timeoutId);
      }

      console.error(`[EvalHttpServer] /eval/run completed (id=${requestId}, messages=${result.messages.length})`);
      this.sendJson(res, 200, result);
    } catch (error) {
      console.error(`[EvalHttpServer] /eval/run failed (id=${requestId}):`, error);
      const status = error instanceof Error && error.message.includes('timed out') ? 504 : 500;
      this.sendJson(res, status, {
        error: `run failed: ${error instanceof Error ? error.message : String(error)}`,
      });
    } finally {
      this.activeRuns--;
    }
  }

  /**
   * Handle POST /eval/judge — raw LLM call, no agent loop.
   */
  private async handleJudge(body: unknown, res: http.ServerResponse): Promise<void> {
    const parseResult = JudgeBodySchema.safeParse(body);
    if (!parseResult.success) {
      const detail = parseResult.error.issues
        .map((i) => `${i.path.join('.')}: ${i.message}`)
        .join('; ');
      this.sendJson(res, 400, { error: `Invalid request body: ${detail}` });
      return;
    }

    const judgeRequest: JudgeRequest = {
      type: 'judge',
      messages: parseResult.data.messages,
    };

    try {
      console.error('[EvalHttpServer] /eval/judge started');
      const result = await this.judgeRunner.run(judgeRequest);
      console.error('[EvalHttpServer] /eval/judge completed');
      // Return { content: "..." } directly (not wrapped in { type: "judge_result" })
      this.sendJson(res, 200, { content: result.content });
    } catch (error) {
      console.error('[EvalHttpServer] /eval/judge failed:', error);
      this.sendJson(res, 500, {
        error: `judge failed: ${error instanceof Error ? error.message : String(error)}`,
      });
    }
  }

  /**
   * Read and parse JSON body from an incoming request.
   * Uses a `responded` guard to prevent double-response when req.destroy()
   * is called for oversized payloads (the 'end' event may still fire).
   */
  private readJsonBody(
    req: http.IncomingMessage,
    res: http.ServerResponse,
    onSuccess: (body: unknown) => void
  ): void {
    let data = '';
    let responded = false;
    req.on('data', (chunk: Buffer) => {
      data += chunk.toString();
      if (!responded && data.length > MAX_BODY_SIZE) {
        responded = true;
        req.destroy();
        this.sendJson(res, 413, { error: 'Request body too large' });
      }
    });
    req.on('end', () => {
      if (responded) return;
      responded = true;
      try {
        const body = JSON.parse(data);
        onSuccess(body);
      } catch {
        this.sendJson(res, 400, { error: 'Invalid JSON in request body' });
      }
    });
    req.on('error', () => {
      if (responded) return;
      responded = true;
      this.sendJson(res, 400, { error: 'Error reading request body' });
    });
  }

  /**
   * Verify Bearer token. Returns true if authenticated, false if response was sent with 401.
   */
  private checkAuth(req: http.IncomingMessage, res: http.ServerResponse): boolean {
    const authHeader = req.headers['authorization'] || '';
    const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : '';
    if (token !== this.authToken) {
      this.sendJson(res, 401, { error: 'Unauthorized — supply Authorization: Bearer <token>' });
      return false;
    }
    return true;
  }

  /**
   * Send a JSON response.
   */
  private sendJson(res: http.ServerResponse, statusCode: number, body: unknown): void {
    const json = JSON.stringify(body);
    res.writeHead(statusCode, {
      'Content-Type': 'application/json',
    });
    res.end(json);
  }

  /**
   * Parse --eval-port=NNNN from command line args.
   */
  private getPortFromArgs(): number | undefined {
    const portArg = process.argv.find((arg) => arg.startsWith('--eval-port='));
    if (portArg) {
      const port = parseInt(portArg.split('=')[1], 10);
      if (!isNaN(port) && port > 0 && port < 65536) {
        return port;
      }
    }
    return undefined;
  }
}
