/**
 * Parser coverage supplement tests.
 * Targets uncovered branches in parser.ts.
 */

import { describe, it, expect } from 'vitest';
import {
  parseMcpConfig,
  parseVSCodeConfigToInternal,
  formatToStandardJson,
  formatToMcpServersWrapper,
  formatToVSCodeSettings,
  formatToVSCodeMcpJson,
  isExampleConfiguration,
} from '../parser';

// ── parseMcpConfig uncovered branches ─────────────────────────────────────────

describe('parseMcpConfig — additional branches', () => {
  it('cleans invisible chars: NBSP \\u00A0', () => {
    const input = '{ "command": "npx", "args": [] }';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.config.command).toBe('npx');
  });

  it('cleans invisible chars: narrow no-break space \\u202F', () => {
    const input = '{ "command": "uvx", "args": [] }';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
  });

  it('cleans invisible chars: zero-width space \\u200B', () => {
    const input = '{"command":​"node","args":[]}';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
  });

  it('cleans invisible chars: BOM \\uFEFF', () => {
    const input = '﻿{"command":"node","args":[]}';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
  });

  it('cleans invisible chars: word joiner \\u2060 and zero-width joiner \\u200D', () => {
    const input = '{"command":"no⁠de","args":[]}';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.config.command).toBe('node');
  });

  it('cleans invisible chars: Mongolian vowel separator \\u180E', () => {
    const input = '{"command":"node᠎","args":[]}';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
  });

  it('Format 9: server fragment with URL, no type (StreamableHttp)', () => {
    const input = JSON.stringify({ myServer: { url: 'http://localhost/mcp' } });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
    expect(result.data?.serverName).toBe('myServer');
    expect(result.data?.detectedFormat).toContain('StreamableHttp minimal');
  });

  it('Format 10: server fragment with command, no type (stdio)', () => {
    const input = JSON.stringify({ myTool: { command: 'node', args: ['s.js'] } });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
    expect(result.data?.detectedFormat).toContain('Stdio minimal');
  });

  it('server fragment detects serverName from extractedConfig.serverName', () => {
    // When extractedConfig already has serverName (from extractConfigFromFormat)
    const input = JSON.stringify({ myTool: { command: 'node', args: [] } });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.serverName).toBe('myTool');
    expect(result.data?.isAutoGenerated).toBe(false);
  });

  it('SSE detection: URL includes /mcp/sse path', () => {
    const input = JSON.stringify({ url: 'http://host/mcp/sse' });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('SSE detection: URL ends with /sse', () => {
    const input = JSON.stringify({ url: 'http://host/stream/sse' });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('autoDetect with currentType=sse keeps sse when URL has no sse pattern', () => {
    const input = JSON.stringify({ url: 'http://localhost:3000/api' });
    const result = parseMcpConfig(input, 'sse');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('autoDetect with currentType=stdio changes to StreamableHttp for URL input', () => {
    const input = JSON.stringify({ url: 'http://localhost/api' });
    const result = parseMcpConfig(input, 'stdio');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('autoDetect fallback returns currentType when no command/url', () => {
    const input = JSON.stringify({ env: { KEY: 'val' } });
    const result = parseMcpConfig(input, 'sse');
    // Falls through to (currentType as any) || 'stdio'
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('autoDetect defaults to stdio when no currentType and no command/url', () => {
    const input = JSON.stringify({ env: { KEY: 'val' } });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
  });

  it('getTransportTypeFromTypeField: SSE type', () => {
    const input = JSON.stringify({
      mcpServers: { srv: { url: 'http://x', type: 'sse' } }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
    expect(result.data?.detectedFormat).toContain('StreamableHttp complete');
  });

  it('getTransportTypeFromTypeField: streamable-http variant', () => {
    const input = JSON.stringify({
      mcpServers: { srv: { url: 'http://x', type: 'streamable-http' } }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('getTransportTypeFromTypeField: StreamableHttp variant', () => {
    const input = JSON.stringify({
      mcpServers: { srv: { url: 'http://x', type: 'StreamableHttp' } }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('getTransportTypeFromTypeField: unknown type defaults to StreamableHttp', () => {
    const input = JSON.stringify({
      mcpServers: { srv: { url: 'http://x', type: 'grpc' } }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('Format 3 (mcpServers + type) detects StreamableHttp detectedFormat', () => {
    const input = JSON.stringify({
      mcpServers: { srv: { url: 'http://x/mcp', type: 'http' } }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.detectedFormat).toContain('StreamableHttp complete');
  });

  it('Format 5 (server fragment + type=http) detectedFormat says StreamableHttp server fragment', () => {
    const input = JSON.stringify({ mySrv: { url: 'http://x', type: 'http' } });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.detectedFormat).toContain('StreamableHttp server fragment');
  });

  it('Format 6 (server fragment + type=stdio) detectedFormat says Stdio server fragment', () => {
    const input = JSON.stringify({ mySrv: { command: 'node', args: [], type: 'stdio' } });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.detectedFormat).toContain('Stdio server fragment');
  });

  it('env is included for HTTP config when non-empty', () => {
    const input = JSON.stringify({ url: 'http://x', env: { TOKEN: 'abc' } });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.config.env).toEqual({ TOKEN: 'abc' });
  });

  it('mcpServers wrapper with SSE url autodetect (Format 7)', () => {
    const input = JSON.stringify({
      mcpServers: { srv: { url: 'http://host/sse' } }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
    expect(result.data?.detectedFormat).toContain('StreamableHttp simplified');
  });

  it('mcpServers wrapper env included when non-empty (HTTP)', () => {
    const input = JSON.stringify({
      mcpServers: { srv: { url: 'http://x', env: { K: 'v' } } }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.config.env).toEqual({ K: 'v' });
  });
});

// ── parseVSCodeConfigToInternal uncovered branches ────────────────────────────

describe('parseVSCodeConfigToInternal — additional branches', () => {
  it('returns error for invalid JSON', () => {
    const result = parseVSCodeConfigToInternal('{bad json}', 'mcp.json');
    expect(result.success).toBe(false);
    expect(result.error).toContain('Invalid JSON format');
  });

  it('returns error when mcp.servers key missing in settings.json', () => {
    const input = JSON.stringify({ mcp: {} });
    const result = parseVSCodeConfigToInternal(input, 'settings.json');
    expect(result.success).toBe(false);
  });

  it('returns error when servers key missing in mcp.json', () => {
    const input = JSON.stringify({ other: {} });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(false);
    expect(result.error).toContain('No MCP server found');
  });

  it('convertVSCodeTransportType: sse type returns sse', () => {
    const input = JSON.stringify({
      servers: { s: { type: 'sse', url: 'http://x/sse' } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('convertVSCodeTransportType: http type with /mcp URL returns StreamableHttp', () => {
    const input = JSON.stringify({
      servers: { s: { type: 'http', url: 'http://x/mcp' } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('convertVSCodeTransportType: streamablehttp type returns StreamableHttp', () => {
    const input = JSON.stringify({
      servers: { s: { type: 'streamablehttp', url: 'http://x/mcp' } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('convertVSCodeTransportType: no type but has command returns stdio', () => {
    const input = JSON.stringify({
      servers: { s: { command: 'python', args: ['server.py'] } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
  });

  it('convertVSCodeTransportType: no type but has URL with /mcp path (non-sse) → StreamableHttp', () => {
    const input = JSON.stringify({
      servers: { s: { url: 'http://x/mcp/v1' } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('convertVSCodeTransportType: no type, URL with text/event-stream → sse', () => {
    const input = JSON.stringify({
      servers: { s: { url: 'http://x/text/event-stream' } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('convertVSCodeTransportType: no type, no command/url → default stdio', () => {
    const input = JSON.stringify({
      servers: { s: { env: { K: 'v' } } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
  });

  it('convertVSCodeTransportType: unknown type with no url falls to auto-detect stdio', () => {
    const input = JSON.stringify({
      servers: { s: { type: 'grpc', command: 'node' } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
  });

  it('includes env in HTTP config from mcp.json', () => {
    const input = JSON.stringify({
      servers: { s: { url: 'http://x', env: { K: 'v' } } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.config.env).toEqual({ K: 'v' });
  });

  it('omits env when empty', () => {
    const input = JSON.stringify({
      servers: { s: { command: 'node', args: [], env: {} } }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.config.env).toBeUndefined();
  });

  it('detectedFormat includes format name', () => {
    const input = JSON.stringify({
      mcp: { servers: { s: { command: 'n', args: [] } } }
    });
    const result = parseVSCodeConfigToInternal(input, 'settings.json');
    expect(result.success).toBe(true);
    expect(result.data?.detectedFormat).toContain('settings.json');
  });
});

// ── formatToStandardJson with env in HTTP ────────────────────────────────────

describe('formatToStandardJson — HTTP with env', () => {
  it('includes env when present in HTTP config', () => {
    const config = {
      serverName: 't',
      transportType: 'sse' as const,
      config: { url: 'http://x', env: { K: 'v' } },
      isAutoGenerated: false,
      detectedFormat: '',
    };
    const parsed = JSON.parse(formatToStandardJson(config));
    expect(parsed.env).toEqual({ K: 'v' });
  });
});

// ── formatToMcpServersWrapper with env ────────────────────────────────────────

describe('formatToMcpServersWrapper — with env', () => {
  it('includes env in wrapper', () => {
    const config = {
      serverName: 'srv',
      transportType: 'stdio' as const,
      config: { command: 'n', args: [], env: { K: 'v' } },
      isAutoGenerated: false,
      detectedFormat: '',
    };
    const parsed = JSON.parse(formatToMcpServersWrapper(config));
    expect(parsed.mcpServers.srv.env).toEqual({ K: 'v' });
  });

  it('sse transport type in wrapper', () => {
    const config = {
      serverName: 'srv',
      transportType: 'sse' as const,
      config: { url: 'http://x/sse' },
      isAutoGenerated: false,
      detectedFormat: '',
    };
    const parsed = JSON.parse(formatToMcpServersWrapper(config));
    expect(parsed.mcpServers.srv.type).toBe('sse');
  });
});

// ── formatToVSCodeSettings multiple servers ───────────────────────────────────

describe('formatToVSCodeSettings — multiple servers', () => {
  it('formats multiple servers', () => {
    const configs = [
      { name: 'a', transport: 'stdio' as const, command: 'n', args: ['x'] },
      { name: 'b', transport: 'StreamableHttp' as const, url: 'http://y' },
    ];
    const parsed = JSON.parse(formatToVSCodeSettings(configs));
    expect(Object.keys(parsed.mcp.servers)).toHaveLength(2);
    expect(parsed.mcp.servers.a.type).toBe('stdio');
    expect(parsed.mcp.servers.b.type).toBe('http');
  });

  it('stdio with empty args does not include args', () => {
    const configs = [{ name: 's', transport: 'stdio' as const, command: 'x', args: [] }];
    const parsed = JSON.parse(formatToVSCodeSettings(configs));
    expect(parsed.mcp.servers.s.args).toBeUndefined();
  });

  it('sse transport sets type=sse', () => {
    const configs = [{ name: 's', transport: 'sse' as const, url: 'http://x/sse' }];
    const parsed = JSON.parse(formatToVSCodeSettings(configs));
    expect(parsed.mcp.servers.s.type).toBe('sse');
  });
});

// ── formatToVSCodeMcpJson ─────────────────────────────────────────────────────

describe('formatToVSCodeMcpJson — additional branches', () => {
  it('formats multiple servers in mcp.json style', () => {
    const configs = [
      { name: 'a', transport: 'stdio' as const, command: 'n', args: ['x'] },
      { name: 'b', transport: 'sse' as const, url: 'http://y/sse' },
      { name: 'c', transport: 'StreamableHttp' as const, url: 'http://z' },
    ];
    const parsed = JSON.parse(formatToVSCodeMcpJson(configs));
    expect(Object.keys(parsed.servers)).toHaveLength(3);
    expect(parsed.servers.b.type).toBe('sse');
    expect(parsed.servers.c.type).toBe('http');
  });

  it('omits args when empty in mcp.json stdio', () => {
    const configs = [{ name: 's', transport: 'stdio' as const, command: 'n', args: [] }];
    const parsed = JSON.parse(formatToVSCodeMcpJson(configs));
    expect(parsed.servers.s.args).toBeUndefined();
  });

  it('includes env when non-empty', () => {
    const configs = [{ name: 's', transport: 'stdio' as const, command: 'n', args: [], env: { K: 'v' } }];
    const parsed = JSON.parse(formatToVSCodeMcpJson(configs));
    expect(parsed.servers.s.env).toEqual({ K: 'v' });
  });
});
