import { describe, it, expect } from 'vitest';
import {
  parseMcpConfig,
  parseVSCodeConfigToInternal,
  formatToStandardJson,
  formatToMcpServersWrapper,
  formatToVSCodeSettings,
  formatToVSCodeMcpJson,
  isExampleConfiguration,
} from '../parser';

describe('parseMcpConfig', () => {
  it('returns error for empty input', () => {
    const result = parseMcpConfig('');
    expect(result.success).toBe(false);
    expect(result.error).toContain('empty');
  });

  it('returns error for whitespace-only input', () => {
    const result = parseMcpConfig('   ');
    expect(result.success).toBe(false);
  });

  it('returns error for invalid JSON', () => {
    const result = parseMcpConfig('{not json}');
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/Invalid JSON format/);
  });

  it('parses Format 1: stdio basic format with command', () => {
    const input = JSON.stringify({ command: 'npx', args: ['some-mcp'] });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
    expect(result.data?.config.command).toBe('npx');
    expect(result.data?.config.args).toEqual(['some-mcp']);
    expect(result.data?.isAutoGenerated).toBe(true);
  });

  it('parses Format 2: SSE/StreamableHttp basic with URL', () => {
    const input = JSON.stringify({ url: 'http://localhost:3000/mcp' });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
    expect(result.data?.config.url).toBe('http://localhost:3000/mcp');
  });

  it('parses SSE url that contains /sse path', () => {
    const input = JSON.stringify({ url: 'http://localhost:3000/sse' });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('parses Format 3: mcpServers wrapper with StreamableHttp type', () => {
    const input = JSON.stringify({
      mcpServers: {
        myServer: { url: 'http://localhost:8080', type: 'http' }
      }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
    expect(result.data?.serverName).toBe('myServer');
  });

  it('parses Format 4: mcpServers wrapper with stdio type', () => {
    const input = JSON.stringify({
      mcpServers: {
        myTool: { command: 'python', args: ['server.py'], type: 'stdio' }
      }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
    expect(result.data?.serverName).toBe('myTool');
    expect(result.data?.config.command).toBe('python');
  });

  it('parses Format 7: mcpServers wrapper with URL and no type', () => {
    const input = JSON.stringify({
      mcpServers: {
        remoteServer: { url: 'http://api.example.com/mcp' }
      }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
    expect(result.data?.serverName).toBe('remoteServer');
  });

  it('parses Format 8: mcpServers wrapper with command and no type', () => {
    const input = JSON.stringify({
      mcpServers: {
        localServer: { command: 'node', args: ['index.js'] }
      }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
    expect(result.data?.serverName).toBe('localServer');
  });

  it('parses Format 5: server fragment with StreamableHttp type', () => {
    const input = JSON.stringify({
      myFragmentServer: { url: 'http://localhost:9000', type: 'http' }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('StreamableHttp');
    expect(result.data?.serverName).toBe('myFragmentServer');
  });

  it('parses Format 6: server fragment with stdio type', () => {
    const input = JSON.stringify({
      myTool: { command: 'uvx', args: ['my-tool'], type: 'stdio' }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('stdio');
    expect(result.data?.serverName).toBe('myTool');
  });

  it('includes env vars in config when present', () => {
    const input = JSON.stringify({
      command: 'npx',
      args: ['some-mcp'],
      env: { API_KEY: 'secret' }
    });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.config.env).toEqual({ API_KEY: 'secret' });
  });

  it('omits empty env from config', () => {
    const input = JSON.stringify({ command: 'npx', args: [], env: {} });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.config.env).toBeUndefined();
  });

  it('generates server name when not provided', () => {
    const input = JSON.stringify({ command: 'npx', args: [] });
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.serverName).toMatch(/^mcp-server-\d{14}$/);
    expect(result.data?.isAutoGenerated).toBe(true);
  });

  it('respects currentTransportType hint when URL is ambiguous', () => {
    const input = JSON.stringify({ url: 'http://localhost:3000/api' });
    const result = parseMcpConfig(input, 'sse');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('handles invisible characters (NBSP) in input', () => {
    const input = ' { "command": "npx", "args": [] } ';
    const result = parseMcpConfig(input);
    expect(result.success).toBe(true);
    expect(result.data?.config.command).toBe('npx');
  });
});

describe('parseVSCodeConfigToInternal', () => {
  it('parses settings.json format with stdio server', () => {
    const input = JSON.stringify({
      mcp: {
        servers: {
          myServer: { type: 'stdio', command: 'node', args: ['server.js'] }
        }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'settings.json');
    expect(result.success).toBe(true);
    expect(result.data?.serverName).toBe('myServer');
    expect(result.data?.transportType).toBe('stdio');
    expect(result.data?.config.command).toBe('node');
  });

  it('parses mcp.json format with HTTP server', () => {
    const input = JSON.stringify({
      servers: {
        remoteServer: { type: 'http', url: 'http://api.example.com/mcp' }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.serverName).toBe('remoteServer');
    expect(result.data?.transportType).toBe('StreamableHttp');
  });

  it('returns error for empty input', () => {
    const result = parseVSCodeConfigToInternal('', 'settings.json');
    expect(result.success).toBe(false);
  });

  it('returns error when no MCP server found in settings.json', () => {
    const input = JSON.stringify({ editor: { fontSize: 14 } });
    const result = parseVSCodeConfigToInternal(input, 'settings.json');
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/No MCP server/);
  });

  it('returns error when servers list is empty in mcp.json', () => {
    const input = JSON.stringify({ servers: {} });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(false);
  });

  it('treats SSE URL in http type as sse transport', () => {
    const input = JSON.stringify({
      servers: {
        sseServer: { type: 'http', url: 'http://api.example.com/sse' }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.transportType).toBe('sse');
  });

  it('includes env vars from VSCode config', () => {
    const input = JSON.stringify({
      mcp: {
        servers: {
          server1: { type: 'stdio', command: 'node', args: [], env: { TOKEN: 'abc' } }
        }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'settings.json');
    expect(result.success).toBe(true);
    expect(result.data?.config.env).toEqual({ TOKEN: 'abc' });
  });

  it('sets isAutoGenerated to false for VSCode format', () => {
    const input = JSON.stringify({
      servers: {
        myServer: { type: 'stdio', command: 'npx', args: [] }
      }
    });
    const result = parseVSCodeConfigToInternal(input, 'mcp.json');
    expect(result.success).toBe(true);
    expect(result.data?.isAutoGenerated).toBe(false);
  });
});

describe('formatToStandardJson', () => {
  it('formats stdio config to JSON', () => {
    const config = {
      serverName: 'test',
      transportType: 'stdio' as const,
      config: { command: 'node', args: ['server.js'] },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const result = formatToStandardJson(config);
    const parsed = JSON.parse(result);
    expect(parsed.command).toBe('node');
    expect(parsed.args).toEqual(['server.js']);
    expect(parsed.url).toBeUndefined();
  });

  it('formats HTTP config to JSON', () => {
    const config = {
      serverName: 'test',
      transportType: 'StreamableHttp' as const,
      config: { url: 'http://localhost:3000' },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const result = formatToStandardJson(config);
    const parsed = JSON.parse(result);
    expect(parsed.url).toBe('http://localhost:3000');
    expect(parsed.command).toBeUndefined();
  });

  it('includes env vars when present', () => {
    const config = {
      serverName: 'test',
      transportType: 'stdio' as const,
      config: { command: 'node', args: [], env: { KEY: 'val' } },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const result = formatToStandardJson(config);
    const parsed = JSON.parse(result);
    expect(parsed.env).toEqual({ KEY: 'val' });
  });
});

describe('formatToMcpServersWrapper', () => {
  it('wraps stdio config with mcpServers', () => {
    const config = {
      serverName: 'myServer',
      transportType: 'stdio' as const,
      config: { command: 'python', args: ['main.py'] },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const result = JSON.parse(formatToMcpServersWrapper(config));
    expect(result.mcpServers.myServer.command).toBe('python');
    expect(result.mcpServers.myServer.type).toBe('stdio');
  });

  it('wraps HTTP config with mcpServers', () => {
    const config = {
      serverName: 'httpServer',
      transportType: 'StreamableHttp' as const,
      config: { url: 'http://example.com/mcp' },
      isAutoGenerated: false,
      detectedFormat: ''
    };
    const result = JSON.parse(formatToMcpServersWrapper(config));
    expect(result.mcpServers.httpServer.url).toBe('http://example.com/mcp');
    expect(result.mcpServers.httpServer.type).toBe('StreamableHttp');
  });
});

describe('formatToVSCodeSettings', () => {
  it('formats stdio servers to VSCode settings.json style', () => {
    const configs = [
      { name: 'server1', transport: 'stdio' as const, command: 'node', args: ['index.js'] }
    ];
    const result = JSON.parse(formatToVSCodeSettings(configs));
    expect(result.mcp.servers.server1.type).toBe('stdio');
    expect(result.mcp.servers.server1.command).toBe('node');
    expect(result.mcp.servers.server1.args).toEqual(['index.js']);
  });

  it('formats SSE servers to VSCode settings.json style', () => {
    const configs = [
      { name: 'sseServer', transport: 'sse' as const, url: 'http://localhost/sse' }
    ];
    const result = JSON.parse(formatToVSCodeSettings(configs));
    expect(result.mcp.servers.sseServer.type).toBe('sse');
    expect(result.mcp.servers.sseServer.url).toBe('http://localhost/sse');
  });

  it('formats StreamableHttp servers', () => {
    const configs = [
      { name: 'httpServer', transport: 'StreamableHttp' as const, url: 'http://localhost/mcp' }
    ];
    const result = JSON.parse(formatToVSCodeSettings(configs));
    expect(result.mcp.servers.httpServer.type).toBe('http');
  });

  it('includes env when present', () => {
    const configs = [
      { name: 's', transport: 'stdio' as const, command: 'x', args: [], env: { FOO: 'bar' } }
    ];
    const result = JSON.parse(formatToVSCodeSettings(configs));
    expect(result.mcp.servers.s.env).toEqual({ FOO: 'bar' });
  });

  it('omits args when empty', () => {
    const configs = [{ name: 's', transport: 'stdio' as const, command: 'x', args: [] }];
    const result = JSON.parse(formatToVSCodeSettings(configs));
    expect(result.mcp.servers.s.args).toBeUndefined();
  });
});

describe('formatToVSCodeMcpJson', () => {
  it('formats to VSCode mcp.json format with servers and inputs', () => {
    const configs = [
      { name: 'server1', transport: 'stdio' as const, command: 'node', args: ['s.js'] }
    ];
    const result = JSON.parse(formatToVSCodeMcpJson(configs));
    expect(result.servers).toBeDefined();
    expect(result.inputs).toEqual([]);
    expect(result.servers.server1.command).toBe('node');
  });
});

describe('isExampleConfiguration', () => {
  it('detects stdio example template', () => {
    const stdioExample = `{
  "command": "npx|uvx|python|...",
  "args": [
    "xxx",
    "yyy"
  ],
  "env": {
    "ENV_VAR1": "value1",
    "ENV_VAR2": "value2"
  }
}`;
    expect(isExampleConfiguration(stdioExample)).toBe(true);
  });

  it('detects SSE example template', () => {
    const sseExample = `{
  "url": "http://0.0.0.0:8000/sse"
}`;
    expect(isExampleConfiguration(sseExample)).toBe(true);
  });

  it('returns false for real configuration', () => {
    const realConfig = JSON.stringify({ command: 'node', args: ['server.js'] });
    expect(isExampleConfiguration(realConfig)).toBe(false);
  });
});
