import React, { useState, useEffect, useRef } from 'react';
import { Settings, Folder, Mail } from 'lucide-react';
import '../../styles/AskForInfo.css';

/**
 * Single info collection field
 */
export interface InfoInputField {
  key: string;
  label: string;
  type: 'string' | 'int' | 'double' | 'boolean';
  subtype: 'folder' | 'email' | 'normal';
  varName: string;
  required: boolean;
  /** 🔥 Pre-filled value, auto-generated by backend based on current user info (e.g., EMAIL type pre-fills user email) */
  defaultValue?: string;
}

/**
 * 🔥 Header configuration (built by backend)
 */
export interface InfoInputHeader {
  title: string;
}

/**
 * 🔥 Body configuration (built by backend)
 */
export interface InfoInputBody {
  description: string;
}

/**
 * Info collection request item
 */
export interface InfoInputRequest {
  requestId: string;
  fields: InfoInputField[];
  /** Header configuration, contains the complete title built by backend */
  header: InfoInputHeader;
  /** Body configuration, contains the complete description built by backend */
  body: InfoInputBody;
}

interface AskForInfoProps {
  request: InfoInputRequest | null;
  onConfirm: (requestId: string, values: Record<string, any>) => void;
  onSkip: (requestId: string) => void;
}

/**
 * AskForInfo - Info collection component
 *
 * Similar to ApprovalBar, used to collect user-input environment variable information
 * Supports different input field types: text, number, boolean
 * Supports special subtypes: folder selection, email auto-generation
 */
const AskForInfo: React.FC<AskForInfoProps> = ({ request, onConfirm, onSkip }) => {
  const [values, setValues] = useState<Record<string, any>>({});
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});
  const fileInputRefs = useRef<Record<string, HTMLInputElement | null>>({});

  // Reset state when request changes
  useEffect(() => {
    if (request) {
      const initialValues: Record<string, any> = {};
      request.fields.forEach(field => {
        if (field.type === 'boolean') {
          initialValues[field.key] = false;
        } else if (field.defaultValue !== undefined && field.defaultValue !== '') {
          // 🔥 Prefer backend-provided defaultValue (e.g., EMAIL type pre-filled by backend)
          initialValues[field.key] = field.defaultValue;
        } else {
          initialValues[field.key] = '';
        }
      });
      setValues(initialValues);
      setValidationErrors({});
    }
  }, [request?.requestId]);

  // If no request, don't render
  if (!request) {
    return null;
  }

  const handleInputChange = (key: string, value: any, field: InfoInputField) => {
    let processedValue = value;

    // Process value based on type
    switch (field.type) {
      case 'int':
        processedValue = value === '' ? '' : parseInt(value, 10);
        break;
      case 'double':
        processedValue = value === '' ? '' : parseFloat(value);
        break;
      case 'boolean':
        processedValue = value;
        break;
      default:
        processedValue = value;
        break;
    }

    setValues(prev => ({ ...prev, [key]: processedValue }));

    // Clear validation error for this field
    if (validationErrors[key]) {
      setValidationErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[key];
        return newErrors;
      });
    }
  };

  const handleFolderSelect = async (key: string) => {
    try {
      if (window.electronAPI?.workspace?.selectFolder) {
        const result = await window.electronAPI.workspace.selectFolder();

        if (result.success && result.folderPath) {
          setValues(prev => ({ ...prev, [key]: result.folderPath }));
          
          // Clear validation error
          if (validationErrors[key]) {
            setValidationErrors(prev => {
              const newErrors = { ...prev };
              delete newErrors[key];
              return newErrors;
            });
          }
        }
      }
    } catch (error) {
      console.error('Error selecting folder:', error);
    }
  };

  const validateValues = (): boolean => {
    const errors: Record<string, string> = {};
    let isValid = true;

    request.fields.forEach(field => {
      const value = values[field.key];

      if (field.required && (value === '' || value === null || value === undefined)) {
        errors[field.key] = 'This field is required';
        isValid = false;
        return;
      }

      if (value === '' || value === null || value === undefined) {
        return; // Not required and empty, skip validation
      }

      switch (field.type) {
        case 'int':
          if (typeof value === 'string' && value !== '') {
            const intValue = parseInt(value, 10);
            if (isNaN(intValue)) {
              errors[field.key] = 'Please enter a valid integer';
              isValid = false;
            }
          } else if (typeof value === 'number' && !Number.isInteger(value)) {
            errors[field.key] = 'Please enter a valid integer';
            isValid = false;
          }
          break;
        case 'double':
          if (typeof value === 'string' && value !== '') {
            const floatValue = parseFloat(value);
            if (isNaN(floatValue)) {
              errors[field.key] = 'Please enter a valid number';
              isValid = false;
            }
          } else if (typeof value === 'number' && !isFinite(value)) {
            errors[field.key] = 'Please enter a valid number';
            isValid = false;
          }
          break;
        case 'string':
          if (field.subtype === 'email' && typeof value === 'string' && value !== '') {
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!emailRegex.test(value)) {
              errors[field.key] = 'Please enter a valid email address';
              isValid = false;
            }
          }
          break;
      }
    });

    setValidationErrors(errors);
    return isValid;
  };

  const handleConfirm = () => {
    if (validateValues()) {
      onConfirm(request.requestId, values);
    }
  };

  const handleSkip = () => {
    onSkip(request.requestId);
  };

  const renderField = (field: InfoInputField) => {
    const value = values[field.key] || '';
    const error = validationErrors[field.key];

    return (
      <div key={field.key} className="user-input-field">
        <label className="user-input-label">
          {field.label}
          {field.required && <span className="required-asterisk">*</span>}
        </label>
        
        <div className="input-control-wrapper">
          {field.type === 'boolean' ? (
            <select
              value={value === true ? 'true' : value === false ? 'false' : ''}
              onChange={(e) => handleInputChange(field.key, e.target.value === 'true', field)}
              className={`user-input-control boolean-select ${error ? 'error' : ''}`}
            >
              <option value="">Select value...</option>
              <option value="true">True</option>
              <option value="false">False</option>
            </select>
          ) : field.subtype === 'folder' ? (
            <div className="folder-input-wrapper">
              <input
                type="text"
                value={value}
                onChange={(e) => handleInputChange(field.key, e.target.value, field)}
                placeholder="Select a folder..."
                className={`user-input-control folder-input ${error ? 'error' : ''}`}
                readOnly
              />
              <button
                type="button"
                onClick={() => handleFolderSelect(field.key)}
                className="folder-select-btn"
                title="Select folder"
              >
                <Folder size={16} />
              </button>
            </div>
          ) : field.subtype === 'email' ? (
            <div className="email-input-wrapper">
              <Mail size={16} className="email-icon" />
              <input
                type="email"
                value={value}
                onChange={(e) => handleInputChange(field.key, e.target.value, field)}
                placeholder="user@microsoft.com"
                className={`user-input-control email-input ${error ? 'error' : ''}`}
              />
            </div>
          ) : (
            <input
              type={field.type === 'int' || field.type === 'double' ? 'number' : 'text'}
              value={value}
              onChange={(e) => handleInputChange(field.key, e.target.value, field)}
              step={field.type === 'double' ? 'any' : undefined}
              placeholder={`Enter ${field.label.toLowerCase()}...`}
              className={`user-input-control ${error ? 'error' : ''}`}
            />
          )}
        </div>
        
        {error && <div className="input-error">{error}</div>}
      </div>
    );
  };

  // Directly use header.title from backend
  const headerTitle = request.header.title;

  // 🔥 Directly use body.description from backend (no longer concatenated on frontend)
  const bodyDescription = request.body.description;

  return (
    <div className="ask-for-info">
      {/* Header - top area */}
      <div className="modal-header">
        <div className="header-title-wrapper">
          <Settings size={18} className="header-icon" />
          <h2 className="modal-title">{headerTitle}</h2>
        </div>
      </div>
      
      {/* Body - middle area (scrollable list) */}
      <div className="modal-body">
        <p
          className="modal-description"
          dangerouslySetInnerHTML={{ __html: bodyDescription }}
        />
        <div className="user-input-form">
          {request.fields.map(renderField)}
        </div>
      </div>
      
      {/* Footer - bottom action button area */}
      <div className="modal-footer">
        <button
          type="button"
          onClick={handleSkip}
          className="btn-secondary"
          title="Skip configuration, set up later"
        >
          Skip, Set Up Later
        </button>
        <button
          type="button"
          onClick={handleConfirm}
          className="btn-primary"
          title="Confirm configuration and continue"
        >
          Confirm and Continue
        </button>
      </div>
    </div>
  );
};

export default AskForInfo;