// src/renderer/lib/chat/agentChatSessionCacheManager.ts
// Singleton chat-session state manager for the frontend

import React, { useState, useEffect, useMemo } from 'react';
import { Message } from '../../types/chatTypes';
import { StreamingChunk } from '../../types/streamingTypes';
import { isFeatureEnabled } from '../featureFlags';

/**
 * ChatStatus enum - kept in sync with ChatStatus in backend agentChat.ts
 */
export type ChatStatus =
  | 'idle'
  | 'sending_response'
  | 'compressing_context'
  | 'compressed_context'
  | 'received_response';


/**
 * ThinkingStatus enum
 * - thinking: currently thinking (streaming or waiting for tool results)
 * - thought: thinking complete (final reply received)
 */
export type ThinkingStatus = 'thinking' | 'thought';

/**
 * ChatTurn interface - represents a complete conversation turn
 *
 * A conversation turn consists of:
 * 1. User message
 * 2. AI thinking process (assistant message with tool calls + tool result messages)
 * 3. AI final reply (assistant message without tool calls)
 */
export interface ChatTurn {
  /** User message */
  userMessage: Message;
  
  /** Unique identifier for the thinking section */
  thinkingId: string;
  
  /** Thinking status: 'thinking' (in progress) or 'thought' (complete) */
  thinkingStatus: ThinkingStatus;
  
  /**
   * List of thinking messages.
   * Contains: assistant messages with tool calls and tool result messages.
   * These show the AI's reasoning and tool-use process.
   */
  thinkingMessages: Message[];
  
  /**
   * Final reply message.
   * An assistant message without tool calls.
   * null while still in the 'thinking' state.
   */
  assistantMessage: Message | null;

  /**
   * File paths extracted from the assistant message (without tool calls), cached for
   * frontend rendering to avoid blocking the UI with synchronous extractFilePath calls.
   */
  filePathsInAssistantMessage: CachedFilePath[];
}

/**
 * CachedFilePath interface - cached file path information
 * Contains the file path and whether it exists.
 */
export interface CachedFilePath {
  /** File path */
  path: string;
  /** Whether the file exists */
  exists: boolean;
}

/**
 * StructuredChatHistory interface - structured chat history for rendering
 */
export interface StructuredChatHistory {
  /** System prompt message (if present) */
  systemPrompt: Message | null;
  
  /**
   * Optional assistant Say Hi message.
   * Used for frontend rendering only; not included in the chat context and never sent to the backend.
   * Rendered after systemPrompt and before chatTurns.
   */
  assistantSayHiMessage: Message | null;
  
  /** List of conversation turns */
  chatTurns: ChatTurn[];
}

/**
 * ChatSession cache data structure.
 * Refactored: replaced structuredChatHistory with messages: Message[] for a simpler shape.
 */
export interface ChatSessionCache {
  chatSessionId: string;
  chatId: string;

  // Core change: store a flat message array directly
  messages: Message[];

  chatStatus: ChatStatus;
  streamingMessageId: string | null; // ID of the message currently being streamed
  contextTokenUsage: {
    tokenCount: number;
    totalMessages: number;
    contextMessages: number;
    compressionRatio: number;
  };
  lastUpdated: number;
  // Batch approval request queue - one request per tool
  pendingApprovalRequests?: Array<{
    requestId: string;
    toolCallId: string;
    toolName: string;
    paths: Array<{
      path: string;
      normalizedPath?: string;
    }>;
    message: string;
  }>;
  // Info-collection request
  pendingInfoInputRequest?: {
    requestId: string;
    /** Header config, including the full title built by the backend */
    header: {
      title: string;
    };
    /** Body config, including the full description built by the backend */
    body: {
      description: string;
    };
    fields: Array<{
      key: string;
      label: string;
      type: 'string' | 'int' | 'double' | 'boolean';
      subtype: 'folder' | 'email' | 'normal';
      varName: string;
      required: boolean;
      /** Pre-filled value auto-generated by the backend based on the user's information (e.g. email for EMAIL type) */
      defaultValue?: string;
    }>;
  } | null;
  // Error message for display in ErrorBar
  errorMessage?: string | null;
  // Replay state - pure UI state, does not affect actual chat data
  isReplaying: boolean;
}

/**
 * Direct callback type - used for real-time streaming updates.
 * Invoked synchronously in the same call stack with no async delay.
 */
export type DirectMessageUpdateCallback = (message: Message, chatSessionId: string) => void;
export type CurrentChatSessionIdCallback = (chatSessionId: string | null) => void;

/**
 * AgentChatSessionCacheManager
 * 
 * Responsibilities:
 * 1. Manage currentChatId and currentChatSessionId
 * 2. Manage cache data for all ChatSessions (renderChatHistory, chatStatus, contextTokenUsage)
 * 3. Receive IPC event notifications from the backend AgentChatManager
 * 4. Provide a unified data-access interface and change-subscription mechanism
 * 
 * This is the sole place on the frontend that manages these states.
 */
export class AgentChatSessionCacheManager {
  private static instance: AgentChatSessionCacheManager;
  
  // Currently active ChatId and ChatSessionId
  private currentChatId: string | null = null;
  private currentChatSessionId: string | null = null;
  
  // ChatSession cache pool: chatSessionId -> ChatSessionCache
  private chatSessionCaches: Map<string, ChatSessionCache> = new Map();
  
  // Direct callback management - fix: use Set to support multiple callbacks
  private directMessageUpdateCallbacks: Map<string, Set<DirectMessageUpdateCallback>> = new Map();
  private currentChatSessionIdCallbacks: Set<CurrentChatSessionIdCallback> = new Set();
  
  // IPC event cleanup functions
  private ipcCleanupFunctions: Array<() => void> = [];
  
  private constructor() {
    this.setupIpcListeners();
  }
  
  static getInstance(): AgentChatSessionCacheManager {
    if (!AgentChatSessionCacheManager.instance) {
      AgentChatSessionCacheManager.instance = new AgentChatSessionCacheManager();
    }
    return AgentChatSessionCacheManager.instance;
  }
  
  /**
   * Set up IPC listeners to receive notifications from the backend
   */
  private setupIpcListeners(): void {
    console.log('[AgentChatSessionCacheManager] Setting up IPC listeners');
    
    if (!window.electronAPI?.agentChat) {
      console.error('[AgentChatSessionCacheManager] electronAPI.agentChat not available');
      return;
    }
    
    // 1. Listen for currentChatSessionId changes
    const cleanupCurrentChanged = window.electronAPI.agentChat.onCurrentChatSessionIdChanged?.(
      (data: { chatId: string | null; chatSessionId: string | null }) => {
        this.handleCurrentChatSessionIdChanged(data.chatId, data.chatSessionId);
      }
    );
    if (cleanupCurrentChanged) this.ipcCleanupFunctions.push(cleanupCurrentChanged);
    
    // 2. Listen for ChatSession cache creation
    const cleanupCacheCreated = window.electronAPI.agentChat.onChatSessionCacheCreated?.(
      (data: { chatSessionId: string; chatId: string; initialData?: Partial<ChatSessionCache> }) => {
        this.handleChatSessionCacheCreated(data.chatSessionId, data.chatId, data.initialData);
      }
    );
    if (cleanupCacheCreated) this.ipcCleanupFunctions.push(cleanupCacheCreated);
    
    // 3. Listen for ChatSession cache destruction
    const cleanupCacheDestroyed = window.electronAPI.agentChat.onChatSessionCacheDestroyed?.(
      (data: { chatSessionId: string }) => {
        this.handleChatSessionCacheDestroyed(data.chatSessionId);
      }
    );
    if (cleanupCacheDestroyed) this.ipcCleanupFunctions.push(cleanupCacheDestroyed);
    
    // 4. Listen for chat status changes
    const cleanupStatusChanged = window.electronAPI.agentChat.onChatStatusChanged?.(
      (data: { chatId: string; chatSessionId: string; chatStatus: string; agentName?: string; timestamp?: string }) => {
        // Validate and cast to a legal ChatStatus
        const validStatuses: ChatStatus[] = ['idle', 'sending_response', 'compressing_context', 'compressed_context', 'received_response'];
        const chatStatus = validStatuses.includes(data.chatStatus as ChatStatus)
          ? data.chatStatus as ChatStatus
          : 'idle';
        this.handleChatStatusChanged(data.chatSessionId, chatStatus);
      }
    );
    if (cleanupStatusChanged) this.ipcCleanupFunctions.push(cleanupStatusChanged);
    
    // 5. Listen for context changes
    const cleanupContextChange = window.electronAPI.agentChat.onContextChange?.(
      (data: { chatSessionId: string; stats: any }) => {
        this.handleContextChange(data.chatSessionId, data.stats);
      }
    );
    if (cleanupContextChange) this.ipcCleanupFunctions.push(cleanupContextChange);
    
    // 6. Listen for streaming chunks (update renderChatHistory)
    const cleanupStreamingChunk = window.electronAPI.agentChat.onStreamingChunk?.(
      (chunk: any) => {
        if (chunk.chatSessionId) {
          this.handleStreamingChunk(chunk.chatSessionId, chunk);
        }
      }
    );
    if (cleanupStreamingChunk) this.ipcCleanupFunctions.push(cleanupStreamingChunk);
    
    // 7. Listen for batch approval requests
    const cleanupBatchApproval = window.electronAPI.agentChat.onBatchApprovalRequest?.(
      (data: any) => {
        if (data.chatSessionId) {
          this.handleBatchApprovalRequest(data.chatSessionId, data);
        }
      }
    );
    if (cleanupBatchApproval) this.ipcCleanupFunctions.push(cleanupBatchApproval);
    
    // 8. Listen for approval response processed
    const cleanupApprovalProcessed = window.electronAPI.agentChat.onApprovalResponseProcessed?.(
      (data: any) => {
        if (data.chatSessionId) {
          this.handleApprovalResponseProcessed(data.chatSessionId, data);
        }
      }
    );
    if (cleanupApprovalProcessed) this.ipcCleanupFunctions.push(cleanupApprovalProcessed);
    
    // 9. Listen for info-collection requests
    const cleanupInfoInputRequest = window.electronAPI.agentChat.onUserInfoInputRequest?.(
      (data: any) => {
        if (data.chatSessionId) {
          this.handleUserInfoInputRequest(data.chatSessionId, data);
        }
      }
    );
    if (cleanupInfoInputRequest) this.ipcCleanupFunctions.push(cleanupInfoInputRequest);
    
    // 10. Listen for info-collection response processed
    const cleanupInfoInputProcessed = window.electronAPI.agentChat.onUserInfoInputResponseProcessed?.(
      (data: any) => {
        if (data.chatSessionId) {
          this.handleUserInfoInputResponseProcessed(data.chatSessionId, data);
        }
      }
    );
    if (cleanupInfoInputProcessed) this.ipcCleanupFunctions.push(cleanupInfoInputProcessed);
  }
  
  // ========== IPC Event Handler Methods ==========
  
  /**
   * Handle currentChatSessionId changes
   */
  private handleCurrentChatSessionIdChanged(chatId: string | null, chatSessionId: string | null): void {
    console.log('[AgentChatSessionCacheManager] Current chat session changed:', {
      oldChatId: this.currentChatId,                    // Previous Agent ID (chat_TIMESTAMP_RANDOM)
      oldChatSessionId: this.currentChatSessionId,      // Previous Session ID (chatSession_YYYYMMDDHHMMSS)
      newChatId: chatId,                                // New Agent ID
      newChatSessionId: chatSessionId,                  // New Session ID
      note: 'chatId is Agent ID, chatSessionId is Session ID'
    });
    
    this.currentChatId = chatId;
    this.currentChatSessionId = chatSessionId;
    
    this.notifyCurrentChatSessionIdCallbacks();
  }
  
  /**
   * Handle ChatSession cache creation.
   * Refactored: use renderChatHistory directly as messages; no StructuredChatHistory conversion needed.
   */
  private handleChatSessionCacheCreated(
    chatSessionId: string,
    chatId: string,
    initialData?: Partial<ChatSessionCache>
  ): void {
    console.log('[AgentChatSessionCacheManager] Creating chat session cache:', {
      chatSessionId,              // Session ID (chatSession_YYYYMMDDHHMMSS)
      chatId,                     // Agent ID (chat_TIMESTAMP_RANDOM)
      hasInitialData: !!initialData,
      note: 'Creating new session cache entry'
    });

    // Use renderChatHistory directly; no conversion needed
    let messages: Message[] = [];

    if (initialData?.messages) {
      // New structure: use messages directly
      messages = initialData.messages;
      console.log('[AgentChatSessionCacheManager] Using provided messages:', {
        chatSessionId,
        messageCount: messages.length
      });
    } else if ((initialData as any)?.renderChatHistory && Array.isArray((initialData as any).renderChatHistory)) {
      // Old structure: get from renderChatHistory
      messages = (initialData as any).renderChatHistory as Message[];
      console.log('[AgentChatSessionCacheManager] Using renderChatHistory as messages:', {
        chatSessionId,
        messageCount: messages.length
      });
    }

    // Filter out MCP-injected image messages (user_img_*) so they are never rendered.
    // These are backend-only messages injected by agentChat.ts for vision model consumption.
    if (isFeatureEnabled('browserControl') && messages.length > 0) {
      const beforeCount = messages.length;
      messages = messages.filter(m => !(m.role === 'user' && m.id?.startsWith('user_img_')));
      if (messages.length < beforeCount) {
        console.log('[AgentChatSessionCacheManager] Filtered MCP-injected image messages:', {
          chatSessionId,
          removed: beforeCount - messages.length,
          remaining: messages.length
        });
      }
    }

    // Check whether a cache already exists
    const existingCache = this.chatSessionCaches.get(chatSessionId);

    // Preserve say-hi messages from the existing cache (frontend-only; never fetched from the backend)
    if (existingCache) {
      const existingSayHi = existingCache.messages.find(m => m.id?.startsWith('say-hi-'));
      if (existingSayHi && !messages.find(m => m.id?.startsWith('say-hi-'))) {
        // Insert say-hi message after the system message
        const systemIndex = messages.findIndex(m => m.role === 'system');
        if (systemIndex !== -1) {
          messages.splice(systemIndex + 1, 0, existingSayHi);
        } else {
          messages.unshift(existingSayHi);
        }
        console.log('[AgentChatSessionCacheManager] Preserved assistantSayHiMessage from existing cache:', {
          chatSessionId,
          messageId: existingSayHi.id
        });
      }
    }

    // Create new cache
    const newCache: ChatSessionCache = {
      chatSessionId,
      chatId,
      messages,
      chatStatus: initialData?.chatStatus || 'idle',
      streamingMessageId: initialData?.streamingMessageId || null,
      contextTokenUsage: initialData?.contextTokenUsage || {
        tokenCount: 0,
        totalMessages: 0,
        contextMessages: 0,
        compressionRatio: 1.0
      },
      // Retain AskForInfo and ApprovalRequest state
      pendingApprovalRequests: initialData?.pendingApprovalRequests !== undefined
        ? initialData.pendingApprovalRequests
        : existingCache?.pendingApprovalRequests,
      pendingInfoInputRequest: initialData?.pendingInfoInputRequest !== undefined
        ? initialData.pendingInfoInputRequest
        : existingCache?.pendingInfoInputRequest,
      // Retain errorMessage state
      errorMessage: (initialData as any)?.errorMessage !== undefined
        ? (initialData as any).errorMessage
        : existingCache?.errorMessage,
      // Always reset isReplaying to false (interrupts replay on session switch)
      isReplaying: false,
      lastUpdated: Date.now()
    };

    // Inherit the streaming message ID
    if (existingCache) {
      if (initialData?.streamingMessageId === undefined) {
        newCache.streamingMessageId = existingCache.streamingMessageId;
      }
    }

    this.chatSessionCaches.set(chatSessionId, newCache);

    // If this is an update to an existing cache, fire notifications
    if (existingCache) {
      console.log('[AgentChatSessionCacheManager] Updated existing chat session cache:', {
        chatSessionId,
        preservedStates: ['pendingApprovalRequests', 'pendingInfoInputRequest', 'errorMessage']
      });
      if (chatSessionId === this.currentChatSessionId) {
        this.notifyCurrentChatSessionIdCallbacks();
      }
    }
  }
  
  /**
   * Handle ChatSession cache destruction
   */
  private handleChatSessionCacheDestroyed(chatSessionId: string): void {
    console.log('[AgentChatSessionCacheManager] Destroying chat session cache:', { chatSessionId });
    
    // Optimization: flush all pending batch updates first to avoid losing them
    this.flushPendingUpdatesForSession(chatSessionId);
    
    // Delete the cache
    this.chatSessionCaches.delete(chatSessionId);
    // Fix: clean up all related callbacks
    const callbackSet = this.directMessageUpdateCallbacks.get(chatSessionId);
    if (callbackSet) {
      callbackSet.clear();
      this.directMessageUpdateCallbacks.delete(chatSessionId);
    }
    
    // If this is the currently active chatSession, clear the current state
    if (this.currentChatSessionId === chatSessionId) {
      this.currentChatId = null;
      this.currentChatSessionId = null;
      this.notifyCurrentChatSessionIdCallbacks();
    }
  }
  
  /**
   * Handle chat status changes
   */
  private handleChatStatusChanged(chatSessionId: string, chatStatus: ChatStatus): void {
    console.log('[AgentChatSessionCacheManager] Chat status changed:', {
      chatSessionId,              // Session ID (chatSession_YYYYMMDDHHMMSS)
      chatStatus,
      note: 'Status update for specific session'
    });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    cache.chatStatus = chatStatus;
    cache.lastUpdated = Date.now();

    // Note: updating thinkingStatus is no longer needed after the refactor; related logic removed
  }
  
  /**
   * Handle context changes
   */
  private handleContextChange(chatSessionId: string, stats: any): void {
    console.log('[AgentChatSessionCacheManager] Context changed:', {
      chatSessionId,              // Session ID (chatSession_YYYYMMDDHHMMSS)
      stats,
      note: 'Context token usage updated for session'
    });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    cache.contextTokenUsage = {
      tokenCount: stats.tokenCount || 0,
      totalMessages: stats.totalMessages || 0,
      contextMessages: stats.contextMessages || 0,
      compressionRatio: stats.compressionRatio || 1.0
    };
    cache.lastUpdated = Date.now();
  }
  
  /**
   * Handle a streaming chunk (updates renderChatHistory).
   *
   * New architecture: process raw StreamingChunks directly, maintaining accumulated state internally.
   * Supports:
   * 1. Content chunks  - accumulate text content
   * 2. Tool call chunks - accumulate tool calls
   * 3. Tool result chunks - create tool messages
   * 4. Complete chunks - mark message as complete
   */
  private handleStreamingChunk(chatSessionId: string, chunk: StreamingChunk): void {
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    // Key optimization: set streamingMessageId without creating a placeholder.
    // Let the first content chunk create the real message to avoid an empty placeholder.
    if (chunk.type !== 'complete' && chunk.messageId) {
      if (cache.streamingMessageId !== chunk.messageId) {
        cache.streamingMessageId = chunk.messageId;
        console.log('[AgentChatSessionCacheManager] 🚀 Set streamingMessageId:', {
          chatSessionId: cache.chatSessionId,
          streamingMessageId: chunk.messageId,
          chunkType: chunk.type
        });
      }
    }
    
    // Dispatch based on chunk type.
    // Optimization: each handler immediately notifies listeners, enabling character-by-character rendering.
    switch (chunk.type) {
      case 'content':
        this.handleContentChunk(cache, chunk);
        break;
      case 'tool_call':
        this.handleToolCallChunk(cache, chunk);
        break;
      case 'tool_result':
        this.handleToolResultChunk(cache, chunk);
        break;
      case 'complete':
        this.handleCompleteChunk(cache, chunk);
        break;
      default:
        console.warn('[AgentChatSessionCacheManager] Unknown chunk type:', chunk);
    }
    
    // Notification removed here because each handler already fires it immediately.
    // This avoids duplicate notifications while ensuring every chunk triggers an independent UI update.
  }

  // Note: extractAndCacheFilePaths and extractFilePathsForHistoryMessages were removed in the refactor.
  // File path extraction is now available via the standalone exported function extractFilePathsFromText.

  /**
   * Extract file paths from text (delegates to the standalone exported function)
   */
  private extractFilePathsFromText(text: string): string[] {
    const filePaths: string[] = [];
    const matchedRanges: Array<{start: number, end: number}> = [];
    
    // Windows path regex: matches paths starting with a drive letter
    const windowsPathRegex = /([A-Za-z]:[\\\/](?:[^\\\/<>"'|?*:\n]+[\\\/])*[^\\\/<>"'|?*:\n]*\.[a-zA-Z0-9]+)/gi;
    
    // Unix path regex: matches paths starting with common system directories
    const unixPathRegex = /(\/(?:Users|home|opt|var|etc|usr|Applications|Library|System|private|tmp|bin|sbin|dev|proc|sys|mnt|media|run)(?:\/[^\/\n<>"'|?*:]+)*\/[^\/\n<>"'|?*:]*\.[a-zA-Z0-9]+)/gi;
    
    let match;
    
    // Extract Windows paths first and record match positions
    while ((match = windowsPathRegex.exec(text)) !== null) {
      const rawPath = match[1];
      const matchStart = match.index;
      const matchEnd = match.index + rawPath.length;
      
      // Normalise to backslash format (Windows standard)
      const normalizedPath = rawPath.replace(/\//g, '\\');
      
      filePaths.push(normalizedPath);
      matchedRanges.push({ start: matchStart, end: matchEnd });
    }
    
    // Check whether Unix paths overlap with already-matched Windows paths
    const isOverlapping = (start: number, end: number): boolean => {
      return matchedRanges.some(range =>
        (start >= range.start && start < range.end) ||
        (end > range.start && end <= range.end) ||
        (start <= range.start && end >= range.end)
      );
    };
    
    // Extract Unix paths, skipping any that overlap with Windows paths
    while ((match = unixPathRegex.exec(text)) !== null) {
      const unixPath = match[1];
      const matchStart = match.index;
      const matchEnd = match.index + unixPath.length;
      
      // Skip if this Unix path overlaps with a Windows path
      if (isOverlapping(matchStart, matchEnd)) {
        continue;
      }
      
      filePaths.push(unixPath);
    }
    
    // Deduplicate and return
    return [...new Set(filePaths)];
  }

  /**
   * Add a user message to the messages array.
   * No longer creates a ChatTurn; appends directly to the flat message list.
   */
  addUserMessage(chatSessionId: string, userMessage: Message): void {
    // Filter out MCP-injected image messages
    if (isFeatureEnabled('browserControl') && userMessage.id?.startsWith('user_img_')) {
      return;
    }

    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found:', chatSessionId);
      return;
    }

    cache.messages = [...cache.messages, userMessage];
    cache.lastUpdated = Date.now();

    console.log('[AgentChatSessionCacheManager] Added user message:', {
      chatSessionId,
      messageId: userMessage.id,
      totalMessages: cache.messages.length
    });

    this.triggerDirectMessageUpdate(userMessage, chatSessionId);
  }

  /**
   * Compatibility wrapper to keep legacy API; internally calls the new method.
   * @deprecated Use addUserMessage instead
   */
  addUserMessageAndCreateTurn(chatSessionId: string, userMessage: Message): void {
    this.addUserMessage(chatSessionId, userMessage);
  }

  /**
   * Handle a Content chunk - accumulate text content.
   * Refactored: find and update messages directly in the messages array.
   */
  private handleContentChunk(cache: ChatSessionCache, chunk: StreamingChunk): void {
    if (!chunk.contentDelta) return;

    // Look up the target message in the messages array
    const messageIndex = cache.messages.findIndex(msg => msg.id === chunk.messageId);

    if (messageIndex === -1) {
      // Create a new message and append it
      const newMessage: Message = {
        id: chunk.messageId,
        role: 'assistant',
        content: [{ type: 'text', text: chunk.contentDelta.text }],
        timestamp: chunk.timestamp,
        streamingComplete: false
      };
      cache.messages = [...cache.messages, newMessage];
      cache.lastUpdated = Date.now();
      this.triggerDirectMessageUpdate(newMessage, cache.chatSessionId);
    } else {
      // Update the existing message
      const targetMessage = cache.messages[messageIndex];
      const textContent = targetMessage.content.find((c: any) => c.type === 'text');

      const updatedMessage: Message = {
        ...targetMessage,
        content: textContent
          ? targetMessage.content.map((c: any) =>
              c.type === 'text' ? { type: 'text', text: c.text + chunk.contentDelta!.text } : c
            )
          : [...targetMessage.content, { type: 'text', text: chunk.contentDelta!.text }]
      };

      cache.messages = [
        ...cache.messages.slice(0, messageIndex),
        updatedMessage,
        ...cache.messages.slice(messageIndex + 1)
      ];
      cache.lastUpdated = Date.now();
      this.triggerDirectMessageUpdate(updatedMessage, cache.chatSessionId);
    }
  }
  
  /**
   * Handle a Tool Call chunk - accumulate tool calls.
   * Refactored: find and update messages directly in the messages array.
   */
  private handleToolCallChunk(cache: ChatSessionCache, chunk: StreamingChunk): void {
    if (!chunk.toolCallDelta) return;

    const messageIndex = cache.messages.findIndex(msg => msg.id === chunk.messageId);
    let targetMessage: Message;

    if (messageIndex === -1) {
      // Create a new message
      targetMessage = {
        id: chunk.messageId,
        role: 'assistant',
        content: [{ type: 'text', text: '' }],
        timestamp: chunk.timestamp,
        streamingComplete: false,
        tool_calls: []
      };
      cache.messages = [...cache.messages, targetMessage];
    } else {
      targetMessage = cache.messages[messageIndex];
    }

    const delta = chunk.toolCallDelta;
    const index = delta.index || 0;

    // Initialise or update the tool_calls array
    const toolCalls = targetMessage.tool_calls ? [...targetMessage.tool_calls] : [];

    while (toolCalls.length <= index) {
      toolCalls.push({
        id: '',
        type: 'function',
        function: { name: '', arguments: '' }
      });
    }

    // 🔥 Fix: Create new toolCall object to avoid in-place mutation that React cannot detect
    const oldToolCall = toolCalls[index];
    const updatedToolCall = {
      ...oldToolCall,
      id: delta.id || oldToolCall.id,
      function: {
        ...oldToolCall.function,
        name: delta.function?.name || oldToolCall.function.name,
        arguments: oldToolCall.function.arguments + (delta.function?.arguments || '')
      }
    };
    toolCalls[index] = updatedToolCall;

    const updatedMessage: Message = { ...targetMessage, tool_calls: toolCalls };

    const idx = cache.messages.findIndex(msg => msg.id === chunk.messageId);
    if (idx !== -1) {
      cache.messages = [
        ...cache.messages.slice(0, idx),
        updatedMessage,
        ...cache.messages.slice(idx + 1)
      ];
    }

    cache.lastUpdated = Date.now();

    // 🔥 Fix: Trigger UI update when id, name, or arguments change
    if (delta.id || delta.function?.name || delta.function?.arguments) {
      this.triggerDirectMessageUpdate(updatedMessage, cache.chatSessionId);
    }
  }
  
  /**
   * Handle a Tool Result chunk - create a tool message.
   * Refactored: append tool messages directly to the messages array.
   */
  private handleToolResultChunk(cache: ChatSessionCache, chunk: StreamingChunk): void {
    if (!chunk.toolResult) return;

    // Create the tool message
    const toolMessage: Message = {
      id: chunk.toolResult.tool_call_id,
      role: 'tool',
      content: [{ type: 'text', text: chunk.toolResult.content }],
      tool_call_id: chunk.toolResult.tool_call_id,
      name: chunk.toolResult.tool_name,
      timestamp: chunk.timestamp,
      streamingComplete: true
    };

    // Check whether this tool message already exists
    const existingIndex = cache.messages.findIndex(
      msg => msg.role === 'tool' && msg.id === toolMessage.id
    );

    if (existingIndex !== -1) {
      // Update the existing message
      cache.messages = [
        ...cache.messages.slice(0, existingIndex),
        toolMessage,
        ...cache.messages.slice(existingIndex + 1)
      ];
    } else {
      // Append the new tool message
      cache.messages = [...cache.messages, toolMessage];
    }

    cache.lastUpdated = Date.now();

    this.triggerDirectMessageUpdate(toolMessage, cache.chatSessionId);
  }

  /**
   * Handle a Complete chunk - mark the message as complete.
   * Refactored: update message state directly in the messages array.
   */
  private handleCompleteChunk(cache: ChatSessionCache, chunk: StreamingChunk): void {
    if (!chunk.complete) return;

    const messageIndex = cache.messages.findIndex(msg => msg.id === chunk.complete!.messageId);

    if (messageIndex !== -1) {
      const targetMessage = cache.messages[messageIndex];
      const updatedMessage: Message = {
        ...targetMessage,
        streamingComplete: true
      };

      cache.messages = [
        ...cache.messages.slice(0, messageIndex),
        updatedMessage,
        ...cache.messages.slice(messageIndex + 1)
      ];

      cache.streamingMessageId = null;
      cache.lastUpdated = Date.now();

      this.triggerDirectMessageUpdate(updatedMessage, cache.chatSessionId);

      console.log('[AgentChatSessionCacheManager] Message completed:', {
        chatSessionId: cache.chatSessionId,
        messageId: chunk.complete.messageId,
        hasToolCalls: chunk.complete.hasToolCalls
      });
    }

    // Fire UI update notification
    if (cache.chatSessionId === this.currentChatSessionId) {
      this.notifyCurrentChatSessionIdCallbacks();
    }
  }
  
  /**
   * Handle batch approval requests.
   *
   * Logic:
   * 1. If chatSessionId === currentChatSessionId, render immediately (trigger UI update)
   * 2. If chatSessionId !== currentChatSessionId, only cache; render when the session is switched to
   */
  private handleBatchApprovalRequest(chatSessionId: string, data: any): void {
    console.log('[AgentChatSessionCacheManager] Batch approval request received:', {
      chatSessionId,
      currentChatSessionId: this.currentChatSessionId,
      requestsCount: data.requests?.length || 0,
      isCurrentSession: chatSessionId === this.currentChatSessionId
    });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    // Update pending approval requests in the cache
    cache.pendingApprovalRequests = data.requests || [];
    cache.lastUpdated = Date.now();
    
    // Key: if this is the currently active ChatSession, trigger a UI update immediately
    if (chatSessionId === this.currentChatSessionId) {
      console.log('[AgentChatSessionCacheManager] ✅ Current session - triggering UI update for approval requests');
      // Trigger React re-render by bumping lastUpdated.
      // ChatView reads pendingApprovalRequests via getChatSessionCache().
      this.notifyCurrentChatSessionIdCallbacks();
    } else {
      console.log('[AgentChatSessionCacheManager] 📦 Non-current session - cached for later rendering');
    }
  }
  /**
   * Handle the approval-response-processed event.
   * The backend fires this after processing each approval response; the frontend removes the corresponding item from pendingApprovalRequests.
   */
  private handleApprovalResponseProcessed(chatSessionId: string, data: any): void {
    console.log('[AgentChatSessionCacheManager] Approval response processed:', {
      chatSessionId,
      requestId: data.requestId,
      toolCallId: data.toolCallId,
      path: data.path,
      approved: data.approved
    });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    // Remove the processed request from pendingApprovalRequests
    if (cache.pendingApprovalRequests && cache.pendingApprovalRequests.length > 0) {
      const beforeCount = cache.pendingApprovalRequests.length;
      cache.pendingApprovalRequests = cache.pendingApprovalRequests.filter(
        req => req.requestId !== data.requestId
      );
      const afterCount = cache.pendingApprovalRequests.length;
      
      console.log('[AgentChatSessionCacheManager] Removed approval request from cache:', {
        chatSessionId,
        requestId: data.requestId,
        beforeCount,
        afterCount,
        remaining: cache.pendingApprovalRequests.length
      });
      
      cache.lastUpdated = Date.now();
      
      // Key: if this is the currently active ChatSession, trigger a UI update
      if (chatSessionId === this.currentChatSessionId) {
        console.log('[AgentChatSessionCacheManager] ✅ Current session - triggering UI update after approval response');
        this.notifyCurrentChatSessionIdCallbacks();
      }
    } else {
      console.warn('[AgentChatSessionCacheManager] No pending approval requests found in cache:', {
        chatSessionId,
        requestId: data.requestId
      });
    }
  }
  
  /**
   * Handle an info-collection request.
   * Similar to handleBatchApprovalRequest but for collecting user input.
   */
  private handleUserInfoInputRequest(chatSessionId: string, data: any): void {
    console.log('[AgentChatSessionCacheManager] User info input request received:', {
      chatSessionId,
      currentChatSessionId: this.currentChatSessionId,
      requestId: data.requestId,
      fieldsCount: data.fields?.length || 0,
      isCurrentSession: chatSessionId === this.currentChatSessionId
    });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    // Update the info-collection request in the cache
    cache.pendingInfoInputRequest = {
      requestId: data.requestId,
      header: data.header || { title: 'Configuration' },
      body: data.body || { description: 'Please fill in the following environment variables to complete the MCP server setup.' },
      fields: data.fields || []
    };
    cache.lastUpdated = Date.now();
    
    // Key: if this is the currently active ChatSession, trigger a UI update immediately
    if (chatSessionId === this.currentChatSessionId) {
      console.log('[AgentChatSessionCacheManager] ✅ Current session - triggering UI update for info input request');
      this.notifyCurrentChatSessionIdCallbacks();
    } else {
      console.log('[AgentChatSessionCacheManager] 📦 Non-current session - cached for later rendering');
    }
  }
  
  /**
   * Handle the info-input-response-processed event.
   * The backend fires this after processing the user's confirm or skip response; the frontend clears pendingInfoInputRequest.
   */
  private handleUserInfoInputResponseProcessed(chatSessionId: string, data: any): void {
    console.log('[AgentChatSessionCacheManager] User info input response processed:', {
      chatSessionId,
      requestId: data.requestId,
      action: data.action
    });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    // Clear pendingInfoInputRequest
    if (cache.pendingInfoInputRequest && cache.pendingInfoInputRequest.requestId === data.requestId) {
      console.log('[AgentChatSessionCacheManager] Clearing pendingInfoInputRequest:', {
        chatSessionId,
        requestId: data.requestId,
        action: data.action
      });
      
      cache.pendingInfoInputRequest = null;
      cache.lastUpdated = Date.now();
      
      // Key: if this is the currently active ChatSession, trigger a UI update
      if (chatSessionId === this.currentChatSessionId) {
        console.log('[AgentChatSessionCacheManager] ✅ Current session - triggering UI update after info input response');
        this.notifyCurrentChatSessionIdCallbacks();
      }
    } else {
      console.warn('[AgentChatSessionCacheManager] No matching pendingInfoInputRequest found:', {
        chatSessionId,
        requestId: data.requestId,
        currentRequestId: cache.pendingInfoInputRequest?.requestId
      });
    }
  }
  
  
  // ========== Public API Methods ==========
  
  /**
   * Get the current ChatId
   */
  getCurrentChatId(): string | null {
    return this.currentChatId;
  }
  
  /**
   * Get the current ChatSessionId
   */
  getCurrentChatSessionId(): string | null {
    return this.currentChatSessionId;
  }
  
  /**
   * Manually set the current ChatSessionId (frontend use only; does not affect the backend)
   */
  setCurrentChatSessionId(chatId: string | null, chatSessionId: string | null): void {
    if (this.currentChatId === chatId && this.currentChatSessionId === chatSessionId) {
      return; // No change, skip
    }
    
    this.currentChatId = chatId;
    this.currentChatSessionId = chatSessionId;
    this.notifyCurrentChatSessionIdCallbacks();
  }
  
  /**
   * Get the cache for a specific ChatSession
   */
  getChatSessionCache(chatSessionId: string): ChatSessionCache | null {
    return this.chatSessionCaches.get(chatSessionId) || null;
  }
  
  /**
   * Get the cache for the currently active ChatSession
   */
  getCurrentChatSessionCache(): ChatSessionCache | null {
    if (!this.currentChatSessionId) {
      return null;
    }
    return this.getChatSessionCache(this.currentChatSessionId);
  }
  
  /**
   * Get all ChatSession caches
   */
  getAllChatSessionCaches(): Map<string, ChatSessionCache> {
    return new Map(this.chatSessionCaches);
  }
  
  /**
   * Manually create a ChatSession cache (for frontend-initiated creation)
   */
  createChatSessionCache(chatSessionId: string, chatId: string, initialData?: Partial<ChatSessionCache>): void {
    if (this.chatSessionCaches.has(chatSessionId)) {
      console.warn('[AgentChatSessionCacheManager] Cache already exists:', chatSessionId);
      return;
    }
    
    this.handleChatSessionCacheCreated(chatSessionId, chatId, initialData);
  }
  
  /**
   * Manually update a ChatSession cache.
   * Fix: fire notifications after updating to ensure the UI responds immediately.
   */
  updateChatSessionCache(chatSessionId: string, updates: Partial<ChatSessionCache>): void {
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found:', chatSessionId);
      return;
    }
    
    Object.assign(cache, updates, { lastUpdated: Date.now() });
    
    // Key fix: if messages were updated, fire direct callbacks.
    // This ensures user messages are rendered immediately after being added.
    if (updates.messages && updates.messages.length > 0) {
      const lastMessage = updates.messages[updates.messages.length - 1];
      if (lastMessage) {
        this.triggerDirectMessageUpdate(lastMessage, chatSessionId);
      }
    }
    
    // If this is the currently active session, also fire session callbacks
    if (chatSessionId === this.currentChatSessionId) {
      this.notifyCurrentChatSessionIdCallbacks();
    }
  }

  /**
   * Set the system prompt message
   */
  setSystemPrompt(chatSessionId: string, systemMessage: Message): void {
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) return;

    // Remove existing system messages
    cache.messages = cache.messages.filter(m => m.role !== 'system');
    // Insert the new system message at the beginning of the array
    cache.messages.unshift(systemMessage);
    cache.lastUpdated = Date.now();

    this.triggerDirectMessageUpdate(systemMessage, chatSessionId);
  }

  /**
   * Set the Assistant Say Hi message.
   * Used for frontend rendering only; not included in the chat context and never sent to the backend.
   * @param chatSessionId - ChatSession ID
   * @param markdownContent - Markdown greeting text; pass null or an empty string to clear it
   */
  setAssistantSayHiMessage(chatSessionId: string, markdownContent: string | null): void {
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) return;

    // Remove existing say-hi messages
    cache.messages = cache.messages.filter(m => !m.id?.startsWith('say-hi-'));

    if (markdownContent && markdownContent.trim()) {
      const sayHiMessage: Message = {
        id: `say-hi-${chatSessionId}-${Date.now()}`,
        role: 'assistant',
        content: [{ type: 'text', text: markdownContent }],
        timestamp: Date.now(),
        streamingComplete: true
      };

      // Insert after the system message
      const systemIndex = cache.messages.findIndex(m => m.role === 'system');
      if (systemIndex !== -1) {
        cache.messages.splice(systemIndex + 1, 0, sayHiMessage);
      } else {
        cache.messages.unshift(sayHiMessage);
      }

      cache.lastUpdated = Date.now();
      this.triggerDirectMessageUpdate(sayHiMessage, chatSessionId);
    }

    this.notifyCurrentChatSessionIdCallbacks();
  }
  
  /**
   * Manually delete a ChatSession cache
   */
  deleteChatSessionCache(chatSessionId: string): void {
    this.handleChatSessionCacheDestroyed(chatSessionId);
  }
  
  // ========== Callback Management ==========
  
  registerDirectMessageUpdateCallback(
    chatSessionId: string,
    callback: DirectMessageUpdateCallback
  ): () => void {
    // Fix: use Set to support multiple callbacks
    let callbackSet = this.directMessageUpdateCallbacks.get(chatSessionId);
    if (!callbackSet) {
      callbackSet = new Set();
      this.directMessageUpdateCallbacks.set(chatSessionId, callbackSet);
    }
    callbackSet.add(callback);
    console.log('[AgentChatSessionCacheManager] Registered direct callback for:', chatSessionId, 'total:', callbackSet.size);
    
    return () => {
      const set = this.directMessageUpdateCallbacks.get(chatSessionId);
      if (set) {
        set.delete(callback);
        console.log('[AgentChatSessionCacheManager] Unregistered direct callback for:', chatSessionId, 'remaining:', set.size);
        if (set.size === 0) {
          this.directMessageUpdateCallbacks.delete(chatSessionId);
        }
      }
    };
  }
  
  // Smart batch-update mechanism
  private streamingUpdateQueue: Map<string, {
    message: Message;
    sessionId: string;
    timestamp: number;
    timeout?: NodeJS.Timeout;
  }> = new Map();
  
  /**
   * Flush all pending batch updates for the specified session.
   * Called on cache destruction or session switch to prevent losing updates.
   */
  private flushPendingUpdatesForSession(chatSessionId: string): void {
    const keysToFlush: string[] = [];
    
    // Find all pending updates that belong to this session
    this.streamingUpdateQueue.forEach((update, key) => {
      if (update.sessionId === chatSessionId) {
        keysToFlush.push(key);
      }
    });
    
    // Execute these updates immediately
    keysToFlush.forEach(key => {
      const update = this.streamingUpdateQueue.get(key);
      if (update) {
        // Clear the timeout
        if (update.timeout) {
          clearTimeout(update.timeout);
        }
        // Execute the update immediately
        const callbackSet = this.directMessageUpdateCallbacks.get(chatSessionId);
        if (callbackSet && callbackSet.size > 0) {
          this.executeDirectUpdate(update.message, chatSessionId, callbackSet, true);
        }
        // Remove the entry from the queue
        this.streamingUpdateQueue.delete(key);
      }
    });
    
    if (keysToFlush.length > 0) {
      console.log('[AgentChatSessionCacheManager] 🚿 Flushed pending updates for session:', {
        chatSessionId,
        flushedCount: keysToFlush.length
      });
    }
  }
  
  // Dynamic performance tuning
  private performanceMetrics = {
    recentUpdateTimes: [] as number[],
    avgUpdateTime: 0,
    adaptiveThreshold: 30, // Dynamically adjusted batch threshold
    adaptiveBatchDelay: 25 // Dynamically adjusted batch delay
  };

  /**
   * Trigger a direct message update, used for streaming rendering.
   *
   * Important fix (2026-02-03):
   * Resolves UI freezing when the user navigates away from a ChatSession that is still streaming.
   * 
   * Root cause:
   * When a tool (e.g. write_file) streams a large file, every character fires this method.
   * After the user navigates away, callbacks are gradually unregistered, but streaming updates keep arriving.
   * During the transition (before all callbacks are unregistered), a flood of updates are processed and queued.
   * These operations (array copies, Map operations, setTimeout calls) overwhelm the event loop,
   * making it impossible for the user to click other sessions.
   * 
   * Fix:
   * 1. Return immediately if there are no callbacks or the callback set is empty
   * 2. If chatSessionId is not the active session, only update the cache without triggering UI
   * 3. Re-fetch callbackSet inside the setTimeout callback to avoid stale closure issues
   * 4. Reduce batch-log frequency to prevent console flooding
   */
  private triggerDirectMessageUpdate(message: Message, chatSessionId: string): void {
    const callbackSet = this.directMessageUpdateCallbacks.get(chatSessionId);
    
    // Key fix: return immediately if there are no callbacks or the callback set is empty.
    // This avoids expensive batch-processing after the user navigates away, preventing UI freezing.
    if (!callbackSet || callbackSet.size === 0) {
      return;
    }
    
    // Key fix: if the user has navigated to a different ChatSession, only update the cache without triggering UI.
    // This is the core fix for preventing UI freezing - background session streaming should not block the foreground.
    if (chatSessionId !== this.currentChatSessionId) {
      // Only update lastUpdated in the cache so the user sees fresh data when they switch back
      const cache = this.chatSessionCaches.get(chatSessionId);
      if (cache) {
        cache.lastUpdated = Date.now();
      }
      return;
    }
    
    const startTime = performance.now();
    
    // Optimization: for complete-state messages, execute the update immediately without batch delay.
    // This is a defensive measure against the 'HTML generation keeps spinning' issue.
    if ((message as any).streamingComplete) {
      this.executeDirectUpdate(message, chatSessionId, callbackSet, false);
      // Also clean up any pending updates for this message
      const messageKey = `${chatSessionId}-${message.id}`;
      const existingUpdate = this.streamingUpdateQueue.get(messageKey);
      if (existingUpdate?.timeout) {
        clearTimeout(existingUpdate.timeout);
      }
      this.streamingUpdateQueue.delete(messageKey);
      return;
    }
    
    // Smart batch strategy: use dynamically adjusted threshold
    const messageKey = `${chatSessionId}-${message.id}`;
    const existingUpdate = this.streamingUpdateQueue.get(messageKey);
    const now = Date.now();
    
    if (existingUpdate && (now - existingUpdate.timestamp) < this.performanceMetrics.adaptiveThreshold) {
      // Less than the dynamic threshold since the last update; defer to batch
      if (existingUpdate.timeout) {
        clearTimeout(existingUpdate.timeout);
      }
      
      // Fix: re-fetch callbackSet inside setTimeout to use the latest state.
      // Avoids calling stale callbacks captured by the closure.
      const batchTimeout = setTimeout(() => {
        const currentCallbackSet = this.directMessageUpdateCallbacks.get(chatSessionId);
        // Double-check: make sure the session is still active and has callbacks
        if (currentCallbackSet && currentCallbackSet.size > 0 && chatSessionId === this.currentChatSessionId) {
          this.executeDirectUpdate(message, chatSessionId, currentCallbackSet, true);
        }
        this.streamingUpdateQueue.delete(messageKey);
      }, this.performanceMetrics.adaptiveBatchDelay);
      
      this.streamingUpdateQueue.set(messageKey, {
        message,
        sessionId: chatSessionId,
        timestamp: now,
        timeout: batchTimeout
      });
      
      // Reduce log frequency: only log on the first batch to avoid flooding
      if (!existingUpdate) {
        console.log(`[AgentChatSessionCacheManager] 📦 Adaptive batching (${this.performanceMetrics.adaptiveThreshold}ms/${this.performanceMetrics.adaptiveBatchDelay}ms) for:`, chatSessionId);
      }
    } else {
      // Exceeds the dynamic threshold since the last update (or first update); execute immediately
      this.executeDirectUpdate(message, chatSessionId, callbackSet, false);
      this.streamingUpdateQueue.set(messageKey, {
        message,
        sessionId: chatSessionId,
        timestamp: now
      });
    }
  }

  private executeDirectUpdate(
    message: Message, 
    chatSessionId: string, 
    callbackSet: Set<DirectMessageUpdateCallback>, 
    isBatched: boolean
  ): void {
    const startTime = performance.now();
    const updateType = isBatched ? 'batched' : 'immediate';
    
    console.log(`[AgentChatSessionCacheManager] 🔥 Triggering ${callbackSet.size} direct callbacks (${updateType}) for:`, chatSessionId);
    
    // Use normal React scheduling to avoid 'Maximum update depth exceeded' from flushSync
    callbackSet.forEach(callback => {
      try {
        callback(message, chatSessionId);
      } catch (error) {
        console.error(`[AgentChatSessionCacheManager] Error in ${updateType} callback:`, error);
      }
    });
    
    const endTime = performance.now();
    const duration = endTime - startTime;
    
    // Dynamic performance adjustment
    this.updatePerformanceMetrics(duration);
    
    if (duration > 8) { // Lower log threshold for more sensitive performance monitoring
      console.log(`[AgentChatSessionCacheManager] ⚡ ${updateType} update took:`, duration.toFixed(2) + 'ms');
    }
  }

  // Update performance metrics and dynamically adjust parameters
  private updatePerformanceMetrics(duration: number): void {
    this.performanceMetrics.recentUpdateTimes.push(duration);
    
    // Keep only the last 20 performance samples
    if (this.performanceMetrics.recentUpdateTimes.length > 20) {
      this.performanceMetrics.recentUpdateTimes = this.performanceMetrics.recentUpdateTimes.slice(-20);
    }
    
    // Calculate the average update duration
    this.performanceMetrics.avgUpdateTime = 
      this.performanceMetrics.recentUpdateTimes.reduce((a, b) => a + b, 0) / 
      this.performanceMetrics.recentUpdateTimes.length;
    
    // Dynamically adjust parameters: increase batch threshold and delay if performance degrades
    if (this.performanceMetrics.avgUpdateTime > 100) {
      this.performanceMetrics.adaptiveThreshold = Math.min(60, this.performanceMetrics.adaptiveThreshold + 5);
      this.performanceMetrics.adaptiveBatchDelay = Math.min(40, this.performanceMetrics.adaptiveBatchDelay + 3);
    } else if (this.performanceMetrics.avgUpdateTime < 20) {
      this.performanceMetrics.adaptiveThreshold = Math.max(20, this.performanceMetrics.adaptiveThreshold - 2);
      this.performanceMetrics.adaptiveBatchDelay = Math.max(15, this.performanceMetrics.adaptiveBatchDelay - 2);
    }
  }
  
  subscribeToCurrentChatSessionId(callback: CurrentChatSessionIdCallback): () => void {
    this.currentChatSessionIdCallbacks.add(callback);
    callback(this.currentChatSessionId);
    
    return () => {
      this.currentChatSessionIdCallbacks.delete(callback);
    };
  }
  
  private notifyCurrentChatSessionIdCallbacks(): void {
    this.currentChatSessionIdCallbacks.forEach(callback => {
      try {
        callback(this.currentChatSessionId);
      } catch (error) {
        console.error('[AgentChatSessionCacheManager] Error in current session callback:', error);
      }
    });
  }
  
  // ========== Replay Methods ==========

  /**
   * Set the replay status of a ChatSession.
   * isReplaying is a pure UI state and does not affect actual chat data.
   */
  setReplayingStatus(chatSessionId: string, isReplaying: boolean): void {
    console.log('[Replay] setReplayingStatus:', { chatSessionId, isReplaying });
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] setReplayingStatus: cache not found for:', chatSessionId);
      return;
    }

    cache.isReplaying = isReplaying;
    cache.lastUpdated = Date.now();

    if (chatSessionId === this.currentChatSessionId) {
      this.notifyCurrentChatSessionIdCallbacks();
    }
  }

  // ========== Error Message Methods ==========
  
  /**
   * Set the error message for a ChatSession.
   * Used to display an error in the ErrorBar.
   */
  setErrorMessage(chatSessionId: string, errorMessage: string): void {
    console.log('[AgentChatSessionCacheManager] Setting error message:', {
      chatSessionId,
      errorMessage: errorMessage.substring(0, 100) + (errorMessage.length > 100 ? '...' : '')
    });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    cache.errorMessage = errorMessage;
    cache.lastUpdated = Date.now();
    
    // Trigger UI update
    if (chatSessionId === this.currentChatSessionId) {
      this.notifyCurrentChatSessionIdCallbacks();
    }
  }
  
  /**
   * Clear the error message for a ChatSession.
   * Called when the user clicks Retry or the error has been handled.
   */
  clearErrorMessage(chatSessionId: string): void {
    console.log('[AgentChatSessionCacheManager] Clearing error message:', { chatSessionId });
    
    const cache = this.chatSessionCaches.get(chatSessionId);
    if (!cache) {
      console.warn('[AgentChatSessionCacheManager] Cache not found for chatSessionId:', chatSessionId);
      return;
    }
    
    cache.errorMessage = null;
    cache.lastUpdated = Date.now();
    
    // Trigger UI update
    if (chatSessionId === this.currentChatSessionId) {
      this.notifyCurrentChatSessionIdCallbacks();
    }
  }
  
  // ========== Cleanup Methods ==========
  
  /**
   * Clean up all caches and listeners.
   * Important fix: on logout, only clear cache data; retain IPC listeners and React subscriptions
   * so that a new user can still receive backend messages and update the UI after logging in.
   */
  cleanup(): void {
    console.log('[AgentChatSessionCacheManager] Cleaning up');
    
    // Important fix: do NOT clean up IPC listeners!
    // These are needed to receive new session data from the backend when a new user logs in.
    // this.ipcCleanupFunctions.forEach(cleanup => cleanup());
    // this.ipcCleanupFunctions = [];
    
    // Clear all session cache data
    this.chatSessionCaches.clear();
    
    // Clean up direct message callbacks (these are temporarily bound to specific sessions)
    this.directMessageUpdateCallbacks.forEach(set => set.clear());
    this.directMessageUpdateCallbacks.clear();
    
    // Important fix: do NOT clean up currentChatSessionIdCallbacks!
    // These are React hook subscriptions; clearing them would prevent components from receiving new session notifications.
    // this.currentChatSessionIdCallbacks.clear();
    
    // Clear the streaming update queue
    this.streamingUpdateQueue.forEach(update => {
      if (update.timeout) {
        clearTimeout(update.timeout);
      }
    });
    this.streamingUpdateQueue.clear();
    
    // Reset the current session state and notify all subscribers
    const oldChatId = this.currentChatId;
    const oldChatSessionId = this.currentChatSessionId;
    this.currentChatId = null;
    this.currentChatSessionId = null;
    
    // Notify all subscribers that the session has been cleared.
    // This causes React components to update their state.
    console.log('[AgentChatSessionCacheManager] 🔔 Notifying subscribers of cleared session', {
      oldChatId,
      oldChatSessionId,
      newChatId: null,
      newChatSessionId: null
    });
    this.notifyCurrentChatSessionIdCallbacks();
    
    console.log('[AgentChatSessionCacheManager] ✅ Cleanup completed, listeners preserved');
  }
}

/**
 * Standalone exported function that extracts file paths from text.
 * Supports Windows and Unix path formats.
 * Used as a fallback in ChatContainer to extract file paths from assistant messages.
 */
export function extractFilePathsFromText(text: string): string[] {
  const filePaths: string[] = [];
  const matchedRanges: Array<{start: number, end: number}> = [];
  
  // Windows path regex: matches paths starting with a drive letter
  const windowsPathRegex = /([A-Za-z]:[\\\/](?:[^\\\/<>"'|?*:\n]+[\\\/])*[^\\\/<>"'|?*:\n]*\.[a-zA-Z0-9]+)/gi;
  
  // Unix path regex: matches paths starting with common system directories
  const unixPathRegex = /(\/(?:Users|home|opt|var|etc|usr|Applications|Library|System|private|tmp|bin|sbin|dev|proc|sys|mnt|media|run)(?:\/[^\/\n<>"'|?*:]+)*\/[^\/\n<>"'|?*:]*\.[a-zA-Z0-9]+)/gi;
  
  let match;
  
  // Extract Windows paths first and record their match positions
  while ((match = windowsPathRegex.exec(text)) !== null) {
    const rawPath = match[1];
    const matchStart = match.index;
    const matchEnd = match.index + rawPath.length;
    
    // Normalise to backslash format (Windows standard)
    const normalizedPath = rawPath.replace(/\//g, '\\');
    
    filePaths.push(normalizedPath);
    matchedRanges.push({ start: matchStart, end: matchEnd });
  }
  
  // Check whether Unix paths overlap with already-matched Windows paths
  const isOverlapping = (start: number, end: number): boolean => {
    return matchedRanges.some(range =>
      (start >= range.start && start < range.end) ||
      (end > range.start && end <= range.end) ||
      (start <= range.start && end >= range.end)
    );
  };
  
  // Extract Unix paths, skipping those that overlap with Windows paths
  while ((match = unixPathRegex.exec(text)) !== null) {
    const unixPath = match[1];
    const matchStart = match.index;
    const matchEnd = match.index + unixPath.length;
    
    // Skip if this Unix path overlaps with a Windows path
    if (isOverlapping(matchStart, matchEnd)) {
      continue;
    }
    
    filePaths.push(unixPath);
  }
  
  // Deduplicate and return
  return [...new Set(filePaths)];
}

export const agentChatSessionCacheManager = AgentChatSessionCacheManager.getInstance();

export function useCurrentChatSessionId(): string | null {
  const manager = AgentChatSessionCacheManager.getInstance();
  const [sessionId, setSessionId] = useState<string | null>(manager.getCurrentChatSessionId());
  
  useEffect(() => {
    const unsubscribe = manager.subscribeToCurrentChatSessionId((newSessionId) => {
      setSessionId(newSessionId);
    });
    
    return unsubscribe;
  }, []);
  
  return sessionId;
}

/**
 * Reactive hook: get the current chatId (agent ID).
 * Automatically re-renders the component when currentChatId changes.
 * 
 * Note: currentChatId and currentChatSessionId always change together
 * (both updated in handleCurrentChatSessionIdChanged),
 * so we can reuse subscribeToCurrentChatSessionId to watch chatId changes.
 */
export function useCurrentChatId(): string | null {
  const manager = AgentChatSessionCacheManager.getInstance();
  const [chatId, setChatId] = useState<string | null>(manager.getCurrentChatId());
  
  useEffect(() => {
    // currentChatId and currentChatSessionId are updated together in handleCurrentChatSessionIdChanged.
    // Subscribing to currentChatSessionId changes is therefore sufficient to get the latest currentChatId.
    const unsubscribe = manager.subscribeToCurrentChatSessionId(() => {
      setChatId(manager.getCurrentChatId());
    });
    
    return unsubscribe;
  }, []);
  
  return chatId;
}


export function useChatStatus(): ChatStatus {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();
  
  if (!currentSessionId) {
    return 'idle';
  }
  
  const cache = manager.getChatSessionCache(currentSessionId);
  return cache?.chatStatus || 'idle';
}

export function useContextTokenUsage() {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();
  
  if (!currentSessionId) {
    return {
      tokenCount: 0,
      totalMessages: 0,
      contextMessages: 0,
      compressionRatio: 1.0
    };
  }
  
  const cache = manager.getChatSessionCache(currentSessionId);
  return cache?.contextTokenUsage || {
    tokenCount: 0,
    totalMessages: 0,
    contextMessages: 0,
    compressionRatio: 1.0
  };
}

export function useStreamingMessageId(): string | null {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();
  
  if (!currentSessionId) {
    return null;
  }
  
  const cache = manager.getChatSessionCache(currentSessionId);
  return cache?.streamingMessageId || null;
}

/**
 * Hook for error message.
 * Subscribes to error message changes for the current ChatSession.
 * Used to display errors in the ErrorBar.
 */
export function useErrorMessage(): string | null {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  
  useEffect(() => {
    if (!currentSessionId) {
      setErrorMessage(null);
      return;
    }
    
    // Initialise with the current error message
    const cache = manager.getChatSessionCache(currentSessionId);
    setErrorMessage(cache?.errorMessage || null);
    
    // Subscribe to currentChatSessionId changes (fired when the cache is updated)
    const unsubscribe = manager.subscribeToCurrentChatSessionId(() => {
      const updatedCache = manager.getChatSessionCache(currentSessionId);
      setErrorMessage(updatedCache?.errorMessage || null);
    });
    
    return unsubscribe;
  }, [currentSessionId, manager]);
  
  return errorMessage;
}

/**
 * Hook for isReplaying
 * Subscribes to the replay status of the current ChatSession.
 */
export function useIsReplaying(): boolean {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();
  const [isReplaying, setIsReplaying] = useState<boolean>(false);

  useEffect(() => {
    if (!currentSessionId) {
      setIsReplaying(false);
      return;
    }

    // Initialize
    const cache = manager.getChatSessionCache(currentSessionId);
    setIsReplaying(cache?.isReplaying || false);

    // Subscribe to changes
    const unsubscribe = manager.subscribeToCurrentChatSessionId(() => {
      const updatedCache = manager.getChatSessionCache(currentSessionId);
      setIsReplaying(updatedCache?.isReplaying || false);
    });

    return unsubscribe;
  }, [currentSessionId, manager]);

  return isReplaying;
}

/**
 * Hook for pending approval requests.
 * Subscribes to pending approval request changes for the current ChatSession.
 * One request per tool.
 */
export function usePendingApprovalRequests(): Array<{
  requestId: string;
  toolCallId: string;
  toolName: string;
  paths: Array<{
    path: string;
    normalizedPath?: string;
  }>;
  message: string;
}> {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();
  const [requests, setRequests] = useState<any[]>([]);
  
  useEffect(() => {
    if (!currentSessionId) {
      setRequests([]);
      return;
    }
    
    // Initialise with the current requests
    const cache = manager.getChatSessionCache(currentSessionId);
    setRequests(cache?.pendingApprovalRequests || []);
    
    // Subscribe to currentChatSessionId changes (fired when the cache is updated)
    const unsubscribe = manager.subscribeToCurrentChatSessionId(() => {
      const updatedCache = manager.getChatSessionCache(currentSessionId);
      setRequests(updatedCache?.pendingApprovalRequests || []);
    });
    
    return unsubscribe;
  }, [currentSessionId, manager]);
  
  return requests;
}

/**
 * Hook for pending info input request.
 * Subscribes to info-collection request changes for the current ChatSession.
 */
export function usePendingInfoInputRequest(): {
  requestId: string;
  /** Header config, including the full title built by the backend */
  header: {
    title: string;
  };
  /** Body config, including the full description built by the backend */
  body: {
    description: string;
  };
  fields: Array<{
    key: string;
    label: string;
    type: 'string' | 'int' | 'double' | 'boolean';
    subtype: 'folder' | 'email' | 'normal';
    varName: string;
    required: boolean;
    /** Pre-filled value, auto-generated by the backend based on user info (e.g. email for EMAIL type) */
    defaultValue?: string;
  }>;
} | null {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();
  const [request, setRequest] = useState<any>(null);
  
  useEffect(() => {
    if (!currentSessionId) {
      setRequest(null);
      return;
    }
    
    // Initialise with the current request
    const cache = manager.getChatSessionCache(currentSessionId);
    setRequest(cache?.pendingInfoInputRequest || null);
    
    // Subscribe to currentChatSessionId changes (fired when the cache is updated)
    const unsubscribe = manager.subscribeToCurrentChatSessionId(() => {
      const updatedCache = manager.getChatSessionCache(currentSessionId);
      setRequest(updatedCache?.pendingInfoInputRequest || null);
    });
    
    return unsubscribe;
  }, [currentSessionId, manager]);
  
  return request;
}

// ========== Helper Functions ==========
// Note: FINAL_SUMMARY prefix detection logic has been removed.
// tool call presence is now used to determine whether a message is a Final Response.

// ========== History Data Conversion Functions ==========

/**
 * @deprecated No longer needed after the refactor; messages are stored as a flat array.
 * Retained for backward compatibility only.
 *
 * Convert a history message array to StructuredChatHistory.
 * Specifically for loading historical ChatSession data.
 *
 * New conversion logic:
 * - system message -> systemPrompt
 * - Create a ChatTurn on each user Message
 * - Assistant Messages with tool calls + Tool messages -> thinkingMessages
 * - Assistant Message without tool calls -> assistantMessage
 * - Set status to 'thought' when there is no assistantMessage
 *
 * @param messages - history message array from the backend
 * @param chatStatus - current chat status
 * @returns structured chat history
 */
export function convertHistoryToStructuredChatHistory(
  messages: Message[],
  chatStatus?: ChatStatus
): StructuredChatHistory {
  console.log('[convertHistoryToStructuredChatHistory] Converting history messages:', {
    messageCount: messages.length,
    chatStatus
  });
  
  const result: StructuredChatHistory = {
    systemPrompt: null,
    assistantSayHiMessage: null,
    chatTurns: []
  };
  
  let currentTurn: ChatTurn | null = null;
  let turnIndex = 0;
  
  for (const message of messages) {
    // system message -> store directly in systemPrompt
    if (message.role === 'system') {
      result.systemPrompt = message;
      continue;
    }
    
    // On user Message, create a ChatTurn
    if (message.role === 'user') {
      // browserControl feature flag guard: filter out MCP-injected image messages.
      // These are generated by backend agentChat.ts when processing MCP images; only appear when browserControl is enabled.
      if (isFeatureEnabled('browserControl')) {
        if (message.id?.startsWith('user_img_')) {
          continue;
        }
      }
      
      // Save the previous turn
      if (currentTurn) {
        // If the current turn has no assistantMessage, set status to 'thought'
        if (!currentTurn.assistantMessage) {
          currentTurn.thinkingStatus = 'thought';
        }
        result.chatTurns.push(currentTurn);
      }
      
      // Create a new ChatTurn
      currentTurn = {
        userMessage: message, // user message -> user message
        thinkingId: `thinking_${message.id || turnIndex}`, // Generate thinking ID -> thinkingId
        thinkingStatus: 'thinking', // Initial status -> ThinkingStatus
        thinkingMessages: [], // [assistant msgs with tool calls, tool msgs] -> thinkingMessages
        assistantMessage: null, // assistant Message without tool calls -> assistantMessage
        filePathsInAssistantMessage: [] // Initialise as empty array
      };
      turnIndex++;
      continue;
    }
    
    // Skip if there is no currentTurn yet (no user message encountered)
    if (!currentTurn) {
      console.warn('[convertHistoryToStructuredChatHistory] Message before user message, skipping:', message.role);
      continue;
    }
    
    // Handle tool messages - add to thinkingMessages
    if (message.role === 'tool') {
      currentTurn.thinkingMessages.push(message);
      continue;
    }
    
    // Handle assistant message logic
    if (message.role === 'assistant') {
      // Check whether it has tool_calls (assistant message with tool calls)
      if (message.tool_calls && message.tool_calls.length > 0) {
        // Assistant Message with tool calls -> thinkingMessages
        currentTurn.thinkingMessages.push(message);
      } else {
        // Assistant Message without tool calls -> assistantMessage (Final Response)
        currentTurn.assistantMessage = message;
        // Set status to 'thought'
        currentTurn.thinkingStatus = 'thought';
        
        // Note: async file-path extraction is handled elsewhere (requires chatSessionId)
      }
      continue;
    }
  }
  
  // Save the last turn
  if (currentTurn) {
    // Determine the final status based on whether assistantMessage is present
    if (!currentTurn.assistantMessage) {
      // No final reply; determine status from chatStatus
      const isActive = chatStatus === 'sending_response' ||
                       chatStatus === 'compressing_context' ||
                       chatStatus === 'compressed_context';
      // if !assistantMessage: determine ThoughtStatus from chatStatus
      currentTurn.thinkingStatus = isActive ? 'thinking' : 'thought';
    }
    result.chatTurns.push(currentTurn);
  }
  
  console.log('[convertHistoryToStructuredChatHistory] Conversion result:', {
    systemPrompt: !!result.systemPrompt,
    chatTurns: result.chatTurns.length,
    totalThinkingMessages: result.chatTurns.reduce((sum, turn) => sum + turn.thinkingMessages.length, 0),
    assistantMessages: result.chatTurns.filter(turn => turn.assistantMessage).length
  });
  
  return result;
}


/**
 * Hook - get the structured chat history.
 *
 * Converts renderChatHistory to StructuredChatHistory.
 * Used by the optimised chat view.
 *
 * Refactored: returns a flat Message[] instead of StructuredChatHistory
 */
export function useMessages(): Message[] {
  const manager = AgentChatSessionCacheManager.getInstance();
  const currentSessionId = useCurrentChatSessionId();

  const [messages, setMessages] = useState<Message[]>([]);
  const lastCacheUpdateRef = React.useRef<number>(0);

  useEffect(() => {
    if (!currentSessionId) {
      setMessages([]);
      lastCacheUpdateRef.current = 0;
      return;
    }

    // Initialize
    const cache = manager.getChatSessionCache(currentSessionId);
    if (cache) {
      setMessages(cache.messages);
      lastCacheUpdateRef.current = cache.lastUpdated;
    }

    // Subscribe to updates
    const unsubscribe = manager.registerDirectMessageUpdateCallback(
      currentSessionId,
      (message: Message, sessionId: string) => {
        const updatedCache = manager.getChatSessionCache(sessionId);
        if (updatedCache && updatedCache.lastUpdated > lastCacheUpdateRef.current) {
          lastCacheUpdateRef.current = updatedCache.lastUpdated;

          // Use normal React scheduling to avoid 'Maximum update depth exceeded' from flushSync
          setMessages([...updatedCache.messages]);
        }
      }
    );

    return () => unsubscribe();
  }, [currentSessionId, manager]);

  // Subscribe to session switches
  useEffect(() => {
    if (!currentSessionId) return;

    const unsubscribe = manager.subscribeToCurrentChatSessionId(() => {
      const cache = manager.getChatSessionCache(currentSessionId);
      if (cache) {
        setMessages([...cache.messages]);
      }
    });

    return unsubscribe;
  }, [currentSessionId, manager]);

  return useMemo(() => {
    if (!currentSessionId) {
      const cache = manager.getChatSessionCache(currentSessionId || '');
      return cache?.messages || [];
    }
    return messages;
  }, [currentSessionId, messages, manager]);
}

/**
 * Compatibility hook: preserves the legacy API by converting messages back to StructuredChatHistory.
 * @deprecated Use useMessages instead
 */
export function useStructuredChatHistory(): StructuredChatHistory {
  const messages = useMessages();

  return useMemo(() => {
    // Convert flat messages back to StructuredChatHistory format for compatibility
    const result: StructuredChatHistory = {
      systemPrompt: null,
      assistantSayHiMessage: null,
      chatTurns: []
    };

    let currentTurn: ChatTurn | null = null;

    for (const msg of messages) {
      if (msg.role === 'system') {
        result.systemPrompt = msg;
      } else if (msg.id?.startsWith('say-hi-')) {
        result.assistantSayHiMessage = msg;
      } else if (msg.role === 'user') {
        // Create a new turn
        currentTurn = {
          userMessage: msg,
          thinkingId: `thinking_${msg.id || Date.now()}`,
          thinkingStatus: 'thought',
          thinkingMessages: [],
          assistantMessage: null,
          filePathsInAssistantMessage: []
        };
        result.chatTurns.push(currentTurn);
      } else if (msg.role === 'assistant' || msg.role === 'tool') {
        if (currentTurn) {
          // assistant messages with tool_calls, and tool messages, go into thinkingMessages
          if (msg.role === 'tool' || (msg.tool_calls && msg.tool_calls.length > 0)) {
            currentTurn.thinkingMessages.push(msg);
          } else {
            // assistant message without tool_calls is the final reply
            currentTurn.assistantMessage = msg;
          }
        }
      }
    }

    return result;
  }, [messages]);
}
